import { buildCategoryQuestions, QuestionRecord, RawQ } from './programmingQuestions.ts';

// ============================================================================
// CYBERSECURITY — Technology Exploration & Skill Discovery (Easy, Moderate, Difficult)
// ============================================================================

const secEasy: RawQ[] = [
  [
    'What is the core focus of the Cybersecurity domain?',
    'Making computer screens brighter',
    'Protecting computers, networks, user accounts, and sensitive data from unauthorized access, attacks, and damage',
    'Designing 3D video game characters',
    'Writing spreadsheet formulas for sales',
    'B',
    'Cybersecurity safeguards digital systems, personal privacy, and organization data against cyber threats.',
  ],
  [
    'What are the three core goals of the "CIA Triad" in Cybersecurity?',
    'Confidentiality (privacy), Integrity (accuracy/no tampering), and Availability (systems stay accessible to authorized users)',
    'Coding, Internet, and Applications',
    'Computers, Interfaces, and Arrays',
    'Centralization, Installation, and Automation',
    'A',
    'Every security control aims to keep data private (Confidentiality), unmodified (Integrity), and reliably online (Availability).',
  ],
  [
    'What is a "Phishing" attack?',
    'A hardware fan failure',
    'A slow internet connection',
    'A deceptive email, message, or fake website that tricks people into revealing their passwords or banking details',
    'A software update from your operating system',
    'C',
    'Phishing targets human trust rather than technical hardware—always check sender addresses and URLs before entering passwords.',
  ],
  [
    'Why is Multi-Factor Authentication (MFA / 2FA) much safer than using only a password?',
    'It lets you use `"1234"` as your password safely',
    'It removes the need for an email address',
    'It makes login pages load in 3D',
    'Even if someone guesses or steals your password, they still cannot log in without the second factor (such as a code on your phone)',
    'D',
    'MFA combines something you know (password) with something you have (phone/authenticator) or are (fingerprint/face ID).',
  ],
  [
    'When you see `https://` and a lock icon in your browser’s address bar, what does `HTTPS` protect?',
    'It encrypts the communication between your browser and the website so nobody on the network (like public Wi-Fi) can snoop on your data',
    'It guarantees the website has zero typos',
    'It makes your laptop battery last longer',
    'It blocks all advertisements on the page',
    'A',
    'HTTPS uses TLS encryption to keep your login credentials and personal data private while traveling across the internet.',
  ],
  [
    'What is the difference between "Authentication" and "Authorization" in an application?',
    'They mean the exact same thing',
    'Authentication verifies WHO you are (signing in); Authorization checks WHAT you are allowed to access (such as viewing only your own scores)',
    'Authorization happens before you type your email',
    'Authentication is only for printers',
    'B',
    'Logging in is Authentication; ensuring Student A cannot edit Student B’s profile is Authorization.',
  ],
  [
    'Why should websites NEVER store user passwords as plain readable text in their database?',
    'Plain text takes up too much hard drive space',
    'Databases cannot store letters',
    'If the database is ever leaked, attackers would immediately see every user’s real password; instead, passwords must be cryptographically hashed',
    'Plain text slows down CSS rendering',
    'C',
    'Secure systems transform passwords using one-way cryptographic hashing (like bcrypt or Argon2) before storing them.',
  ],
  [
    'What is "Ransomware" in cybersecurity?',
    'A free antivirus tool',
    'A cloud storage backup service',
    'A programming language for routers',
    'Malicious software (malware) that locks or encrypts a victim’s files and demands payment to unlock them',
    'D',
    'Regular offline/cloud backups and keeping software patched are essential defenses against ransomware.',
  ],
  [
    'What is the purpose of a "Firewall" in computer networks?',
    'Monitoring and filtering incoming and outgoing network traffic based on security rules to block unauthorized connections',
    'Physically cooling down hot server rooms',
    'Writing HTML and CSS code',
    'Increasing monitor refresh rates',
    'A',
    'A firewall acts like a security gatekeeper between a trusted network/server and untrusted outside traffic.',
  ],
  [
    'Why is reusing the exact same password across 10 different websites risky?',
    'Websites can detect if you type fast',
    'If just one weak website suffers a data breach, attackers will try that same email and password on your email, banking, and social accounts ("Credential Stuffing")',
    'Browsers only remember one password',
    'Passwords expire after 3 uses',
    'B',
    'Using unique passwords for each account (with the help of a password manager) stops a breach on one site from compromising your other accounts.',
  ],
];

const secModerate: RawQ[] = [
  [
    'What does the "Principle of Least Privilege" mean when designing secure software?',
    'Giving every user and server process only the minimum permissions needed to do their job, rather than full admin access to everything',
    'Allowing only one user to use the website per day',
    'Giving all college students administrator access to the database',
    'Removing all passwords from the system',
    'A',
    'Limiting permissions ensures that if one account or service is compromised, the potential damage is contained.',
  ],
  [
    'How does "Encryption" differ from "Hashing"?',
    'They are identical',
    'Encryption is two-way (data can be decrypted back with a key); Hashing is a one-way fingerprint used to verify passwords and file integrity',
    'Hashing can be reversed with a public password',
    'Encryption deletes the original message permanently',
    'B',
    'Use Encryption when you need to read the data again later (like messages); use Hashing when you only need to verify a match (like passwords).',
  ],
  [
    'What is "Social Engineering" in cybersecurity?',
    'Building a social media app for engineers',
    'Upgrading network switches in an office',
    'Manipulating or tricking people psychologically (e.g., impersonating IT support over the phone) into giving away confidential access',
    'Writing Python scripts for data charts',
    'C',
    'Security is not just about code—training people to recognize impersonation and urgency tricks is equally important.',
  ],
  [
    'In web security, what is Cross-Site Scripting (XSS)?',
    'Using two CSS files on the same page',
    'Connecting a React frontend to an Express backend',
    'Writing code that runs on both Windows and Mac',
    'An attack where malicious JavaScript is injected into a webpage (for example, through an unsanitized comment box) and runs in other users’ browsers',
    'D',
    'Modern frameworks like React automatically escape text variables by default to help protect users against XSS attacks.',
  ],
  [
    'What is a DDoS (Distributed Denial of Service) attack?',
    'Flooding a website or server with massive fake traffic from thousands of devices at once so real users cannot reach it',
    'Deleting a single file on a laptop',
    'Guessing a 4-digit PIN code',
    'Updating a database row with SQL',
    'A',
    'DDoS attacks aim to overwhelm a service’s availability; cloud providers use traffic filtering and CDNs to absorb and block them.',
  ],
  [
    'What does an "Ethical Hacker" (or Penetration Tester) do in the cybersecurity industry?',
    'Steals data from companies illegally',
    'Has official permission from an organization to test its systems for security weaknesses so the team can fix them before real attackers find them',
    'Designs marketing posters for tech companies',
    'Repairs broken laptop hinges',
    'B',
    'Ethical hackers and security engineers play a vital defensive role by finding and fixing vulnerabilities responsibly.',
  ],
  [
    'Why is it important to keep operating systems, browsers, and project libraries updated with security patches?',
    'Updates change the desktop wallpaper',
    'Old software uses more electricity',
    'Updates fix newly discovered security vulnerabilities (CVEs) that attackers actively scan for and exploit',
    'Unpatched software cannot print documents',
    'C',
    'Many cyber incidents happen simply because known vulnerabilities were left unpatched on servers or devices.',
  ],
  [
    'Suppose a student changes the URL in their browser from `/api/results/my_id` to `/api/results/another_student_id`. How must the backend server protect privacy?',
    'Hide the URL bar in the browser',
    'Trust the browser to never change URLs',
    'Show everyone’s results publicly',
    'Verify on the server that the logged-in user actually owns that assessment record before returning any data',
    'D',
    'Server-side ownership verification prevents Broken Access Control (IDOR) and keeps each student’s records private.',
  ],
  [
    'What is a VPN (Virtual Private Network) commonly used for?',
    'Creating an encrypted tunnel for your internet traffic to protect privacy on untrusted networks or securely connect to an organization’s private network',
    'Making your computer processor run at 10 GHz',
    'Replacing the need for passwords on websites',
    'Converting HTML files into PDFs',
    'A',
    'A VPN encrypts traffic between your device and the VPN server, protecting against local network eavesdropping.',
  ],
  [
    'In SkillQuest’s architecture, why is the `SUPABASE_SECRET_KEY` stored only on the Node/Express backend and never in the React frontend?',
    'Because React cannot read string variables',
    'Because the secret key has admin privileges; keeping it on the backend ensures no browser user can ever see or misuse it',
    'Because the key is too long to fit in a `.tsx` file',
    'Because Vite does not support environment variables',
    'B',
    'Separating public client code from secret server credentials is one of the most important real-world security practices.',
  ],
];

const secDifficult: RawQ[] = [
  [
    'What is "Role-Based Access Control" (RBAC) in an application (such as having `Student`, `Faculty`, and `Admin` roles)?',
    'Assigning permissions based on a user’s role so each person can only perform actions appropriate for their responsibility',
    'Letting every user edit the database schema',
    'Requiring users to log in from a specific city',
    'Encrypting CSS files based on screen size',
    'A',
    'RBAC keeps systems organized and secure by tying permissions clearly to user roles.',
  ],
  [
    'In modern cloud and enterprise security, what does a "Zero-Trust" mindset mean?',
    'Never allowing anyone to use the internet',
    '"Never trust, always verify"—verifying identity and permissions on every request rather than assuming everything inside an office network is automatically safe',
    'Deleting all user accounts every night',
    'Not trusting compilers to build code',
    'B',
    'Zero-Trust security verifies identity, device health, and permissions continuously at every layer.',
  ],
  [
    'What is "Defense in Depth" (layered security)?',
    'Putting the server in a deep basement',
    'Using a single 50-character password and no other security controls',
    'Combining multiple independent layers of security (HTTPS, authentication, server validation, database rules, backups) so if one layer fails, others still protect the system',
    'Writing code in multiple languages',
    'C',
    'Just like a bank has perimeter doors, cameras, guards, AND a locked vault, secure software relies on multiple overlapping defenses.',
  ],
  [
    'Why do backend login APIs use "Rate Limiting" (limiting how many login attempts an IP address can make per minute)?',
    'To save electricity on the monitor',
    'Because databases can only read one row per hour',
    'To force users to type slowly',
    'To stop automated bots from trying thousands of guessed passwords per second ("Brute-Force Attacks")',
    'D',
    'Rate limiting protects login endpoints and APIs from automated brute-force guessing and abuse.',
  ],
  [
    'What is the purpose of "Security Logging and Monitoring" in a production application?',
    'Detecting suspicious activity (like repeated failed logins or unusual data access) early and helping engineers investigate incidents',
    'Recording every user’s plaintext password in a public file',
    'Slowing down the website intentionally',
    'Replacing the database',
    'A',
    'Good security logs track important events (without logging sensitive secrets) so teams can spot and respond to threats.',
  ],
  [
    'When a developer installs open-source packages from `npm` or `pip`, what is "Supply-Chain Security"?',
    'Securing physical delivery trucks',
    'Checking that third-party libraries come from trusted sources and scanning them for known security vulnerabilities (`npm audit`)',
    'Writing every operating system from scratch',
    'Disabling the internet while coding',
    'B',
    'Because modern apps rely on open-source packages, keeping dependencies audited and up to date is a key part of software security.',
  ],
  [
    'In database security (such as Supabase PostgreSQL), what does Row-Level Security (RLS) do?',
    'Locks the physical server rack',
    'Prevents tables from having more than 100 rows',
    'Enforces security rules directly inside the database so a user query can only read or modify rows belonging to that user',
    'Encrypts column names into numbers',
    'C',
    'Row-Level Security adds a strong database-level safeguard so each student can only access their own records.',
  ],
  [
    'What is a Digital Certificate (used in HTTPS) and why is it issued by a trusted Certificate Authority (CA)?',
    'A printable PDF diploma for completing a course',
    'A license to buy a domain name',
    'A backup of the website’s HTML',
    'An electronic credential that proves a website genuinely belongs to the real domain owner and provides its public key for encryption',
    'D',
    'Certificate Authorities verify domain ownership so your browser knows `yourbank.com` is authentic and not an impostor.',
  ],
  [
    'How does Cybersecurity connect with every other field in technology (Web, Cloud, AI, Databases)?',
    'Every website, cloud server, database, and AI system needs security built in by design ("Secure by Design") to protect users and data',
    'Cybersecurity is only needed for military computers',
    'Small apps never need authentication or HTTPS',
    'Security is only added 5 years after an app launches',
    'A',
    'Whether you become a web developer, cloud engineer, or security specialist, understanding core cybersecurity principles makes you a far better technologist.',
  ],
  [
    'If you are curious about exploring Cybersecurity further as a student, what is a safe, legal, and effective way to start?',
    'Practice on legal beginner-friendly learning platforms (Capture The Flag / CTF challenges, OWASP Web Security labs) and learn how networks and web apps work',
    'Test attacks on random public websites without permission',
    'Download unknown malware onto your main laptop',
    'Memorize acronyms without learning how networks or web requests work',
    'A',
    'Legal hands-on CTF platforms and understanding how web, network, and operating systems work are the best ways to explore cybersecurity ethically.',
  ],
];

// ============================================================================
// CLOUD COMPUTING — Technology Exploration & Skill Discovery (Easy, Moderate, Difficult)
// ============================================================================

const cloudEasy: RawQ[] = [
  [
    'In simple terms, what is "Cloud Computing"?',
    'Predicting rain and weather patterns using satellites',
    'Renting and using computing power, servers, databases, and storage over the internet on demand instead of buying and maintaining physical servers yourself',
    'Storing files only on a USB pen drive',
    'Running programs without an internet connection',
    'B',
    'Cloud platforms (like AWS, Google Cloud, and Microsoft Azure) let anyone launch servers, databases, and apps over the internet in minutes.',
  ],
  [
    'Which everyday services that students use daily are examples of Cloud Computing?',
    'Google Drive, Gmail, Netflix, Spotify, and online multiplayer games',
    'A wooden bookshelf in a library',
    'A standalone solar pocket calculator',
    'A wired mouse pad',
    'A',
    'Whenever your files, emails, or videos are stored and streamed from remote internet data centers rather than just your local disk, you are using the cloud.',
  ],
  [
    'Why do startups, students, and large companies prefer Cloud Computing over buying their own physical server rooms?',
    'Physical servers are illegal to buy',
    'Cloud servers never use electricity anywhere',
    'You can start instantly with low upfront cost and scale capacity up or down whenever your user traffic changes ("Pay-as-you-go")',
    'Cloud computing does not use the internet',
    'C',
    'Instead of spending lakhs on server hardware upfront, cloud computing lets you start small (often on a free tier) and grow as needed.',
  ],
  [
    'What is a "Virtual Machine" (VM) in the cloud?',
    'A 3D hologram projector',
    'A toy computer for kids',
    'A web browser bookmark',
    'A software-simulated computer running inside a cloud provider’s physical data center that behaves just like a dedicated server',
    'D',
    'Virtualization allows one powerful physical server in a data center to safely run multiple isolated Virtual Machines.',
  ],
  [
    'What is the difference between `IaaS`, `PaaS`, and `SaaS` in cloud computing?',
    'IaaS rents basic virtual servers/storage; PaaS provides a platform to deploy your app code easily; SaaS delivers a complete ready-to-use app (like Gmail or Canva)',
    'They are three different programming languages',
    'SaaS requires you to plug in server cables yourself',
    'All three mean the exact same thing',
    'A',
    'Understanding IaaS (Infrastructure), PaaS (Platform), and SaaS (Software) helps you see the different levels of cloud services.',
  ],
  [
    'If a college result website normally has 50 visitors a day, but suddenly gets 50,000 visitors on exam result day, which cloud feature keeps it from crashing?',
    'Changing the website font color',
    'Auto-Scaling / Elasticity (automatically adding more server capacity during the traffic spike and scaling back down afterward)',
    'Turning off the server during busy hours',
    'Deleting old student accounts',
    'B',
    'Cloud elasticity lets applications handle sudden traffic spikes smoothly without paying for idle servers the rest of the year.',
  ],
  [
    'What is "Cloud Object Storage" (such as AWS S3, Google Cloud Storage, or Supabase Storage) mainly used for?',
    'Running C++ loops',
    'Replacing the CPU fan',
    'Storing and serving files of any size—such as profile pictures, PDF notes, videos, and database backups—reliably in the cloud',
    'Writing HTML tables',
    'C',
    'Cloud object storage is designed to hold millions of uploaded files, images, and backups safely.',
  ],
  [
    'Why do cloud providers have "Regions" (data centers in Mumbai, Singapore, US, Europe) all around the world?',
    'Because servers only work in cold weather',
    'To make cloud dashboards look complicated',
    'Because internet cables cannot cross cities',
    'To host applications close to users for faster loading speeds (lower latency) and to keep services running even if one location has an outage',
    'D',
    'Deploying an app in a nearby region (like Mumbai `ap-south-1` for Indian users) makes every network request faster.',
  ],
  [
    'What does "High Availability" (uptime) mean for a cloud-hosted application?',
    'Designing the system with backup servers so the app stays online and working for users even if one hardware machine fails',
    'Mounting the server on a high shelf',
    'Making the app expensive to use',
    'Only running the app from 9 AM to 5 PM',
    'A',
    'Cloud architectures use redundancy across multiple data centers so users rarely experience downtime.',
  ],
  [
    'Where do the "Cloud" servers actually live physically?',
    'Floating in the sky inside weather clouds',
    'Inside large, secure, climate-controlled facilities called Data Centers filled with thousands of networked servers',
    'Inside your web browser’s cache folder',
    'Inside cell phone towers only',
    'B',
    '"The Cloud" is powered by massive physical data centers connected by high-speed fiber-optic networks around the globe.',
  ],
];

const cloudModerate: RawQ[] = [
  [
    'What problem do "Containers" (like Docker) solve for software developers?',
    'They package an application together with all its required libraries and settings so it runs identically on your laptop, a teammate’s PC, and the cloud server',
    'They physically ship laptops in cardboard boxes',
    'They replace HTML with C++',
    'They make monitors wireless',
    'A',
    'Docker solves the classic "It works on my machine, why did it break on the server?" problem by packaging the app and its environment together.',
  ],
  [
    'What is the role of a "Load Balancer" in a cloud application?',
    'Weighing the physical server rack in kilograms',
    'Distributing incoming user traffic evenly across multiple backend servers so no single server gets overloaded',
    'Deleting half of the incoming user requests',
    'Encrypting the user’s keyboard',
    'B',
    'A Load Balancer sits in front of your servers and routes each user request to a healthy, available server instance.',
  ],
  [
    'What is a CDN (Content Delivery Network)?',
    'A cable TV news channel',
    'A Python library for math',
    'A globally distributed network of edge servers that caches images, CSS, and JS files close to users so websites load much faster',
    'A database table for passwords',
    'C',
    'When you open a fast website, a CDN serves its images and scripts from a city near you rather than fetching them from halfway across the world.',
  ],
  [
    'What does "Serverless Computing" (like Vercel Functions, AWS Lambda, or Cloud Run scale-to-zero) mean for developers?',
    'There are literally zero servers anywhere on Earth',
    'The app can only run offline without a server',
    'You must build your own Linux kernel',
    'You just write and deploy your backend code/functions, and the cloud provider automatically handles running, scaling, and idling the servers for you',
    'D',
    '"Serverless" means *you* don’t have to manage or babysit servers—the cloud runs your code on demand when requests arrive.',
  ],
  [
    'What is a "CI/CD Pipeline" (Continuous Integration / Continuous Deployment) used for in modern cloud workflows?',
    'Automatically testing and deploying your latest code to the live website whenever you push an update to GitHub',
    'Installing air conditioning pipes in an office',
    'Manually copying files via USB drive to 100 computers',
    'Writing SQL queries by hand',
    'A',
    'CI/CD automates building, testing, and deploying code so teams can release improvements safely and quickly.',
  ],
  [
    'What is the difference between a Public Cloud, a Private Cloud, and a Hybrid Cloud?',
    'Public cloud makes all your private passwords public to the world',
    'Public cloud uses shared provider infrastructure (like AWS/GCP) with secure tenant isolation; Private cloud is dedicated to one organization; Hybrid combines both',
    'Private cloud cannot use electricity',
    'Hybrid cloud only runs on smartphones',
    'B',
    'Even on a "Public Cloud" like AWS or Google Cloud, your project’s data and servers are private and isolated unless you choose to make a webpage public.',
  ],
  [
    'Why do cloud engineers place backend databases inside a "Private Subnet" rather than exposing them directly to the public internet?',
    'To make queries run slower',
    'Because databases cannot use IP addresses',
    'So only your own backend application servers can talk to the database, protecting it from direct internet attacks',
    'To save disk space',
    'C',
    'Keeping databases in a private network layer that only your backend API can reach is a core cloud security practice.',
  ],
  [
    'What is the difference between "Vertical Scaling" (Scaling Up) and "Horizontal Scaling" (Scaling Out)?',
    'Vertical scaling turns the monitor sideways; Horizontal scaling lays it flat',
    'They mean the exact same thing',
    'Horizontal scaling deletes servers',
    'Vertical scaling upgrades one server with a bigger CPU/RAM; Horizontal scaling adds more server instances working together behind a load balancer',
    'D',
    'Cloud applications love Horizontal Scaling because you can add or remove server instances seamlessly as traffic changes.',
  ],
  [
    'In cloud computing, what is "Cloud Cost Management" (or avoiding surprise bills) important for?',
    'Monitoring active resources, shutting down unused test servers, and setting budget alerts so you only pay for what you actually need',
    'Making servers run without power',
    'Buying physical gold coins',
    'Deleting production users',
    'A',
    'Because cloud resources are rented on demand, good engineers always set budget alerts and clean up unused test instances.',
  ],
  [
    'What is a "Managed Database Service" (like Supabase, Google Cloud SQL, or AWS RDS)?',
    'A spreadsheet that a human types into manually',
    'A cloud service that runs PostgreSQL/MySQL for you—automatically handling backups, security updates, and high availability',
    'A local `.txt` file on your desktop',
    'A browser extension for CSS',
    'B',
    'Managed cloud databases let developers focus on building their app while the cloud platform takes care of database maintenance and backups.',
  ],
];

const cloudDifficult: RawQ[] = [
  [
    'When an application grows to have dozens of Docker containers running across many cloud servers, what tool is commonly used to orchestrate and manage them?',
    'Kubernetes (or managed container platforms like Cloud Run / ECS)',
    'Microsoft Word',
    'Windows Notepad',
    'A basic HTML table',
    'A',
    'Container orchestration platforms automatically start, restart, scale, and network containers across a cluster of servers.',
  ],
  [
    'What is "Infrastructure as Code" (IaC—using tools like Terraform) in cloud engineering?',
    'Writing frontend CSS inside a database',
    'Defining your cloud servers, networks, and databases in version-controlled config files so your entire cloud setup can be created or recreated automatically',
    'Building physical server racks out of wood',
    'Replacing all backend code with comments',
    'B',
    'Instead of clicking through 50 settings screens by hand, Infrastructure as Code lets teams set up cloud environments reliably from a script.',
  ],
  [
    'What is the difference between a "Monolithic" architecture and a "Microservices" architecture in the cloud?',
    'Monoliths cannot use databases; Microservices cannot use APIs',
    'Microservices require putting all code in a single 1-line file',
    'A Monolith builds and deploys all features as one unified server app; Microservices split a huge system into independent services (e.g., Auth, Payments, Video) that scale separately',
    'Both are types of monitor cables',
    'C',
    'Most student and startup projects should start as a clean, well-structured Monolith, while huge platforms like Netflix use Microservices so different teams can scale independently.',
  ],
  [
    'Why do cloud engineers set up "Health Checks" and "Uptime Monitoring" on deployed applications?',
    'To check if the developer is getting enough sleep',
    'To count how many lines of CSS exist',
    'To make the server use more RAM',
    'So the cloud platform can automatically detect if a server instance becomes unresponsive, restart it, and alert the team if errors spike',
    'D',
    'Automated health checks keep cloud services self-healing and reliable 24/7.',
  ],
  [
    'What are "Logs" and "Metrics" used for in Cloud Observability?',
    'Metrics track numbers over time (CPU usage, request speed, error rate), while Logs record detailed event messages to help debug why an error happened',
    'Logs are wooden timber; Metrics are rulers',
    'They are used only to style login buttons',
    'They delete old database tables',
    'A',
    'When a cloud app has an issue, engineers check Metrics to see *when* it started and Logs to see *what* went wrong.',
  ],
  [
    'In a cloud application (such as ordering a ticket or generating a PDF report), why is a "Background Job Queue" (Message Queue) useful?',
    'It forces the user to stare at a frozen screen for 10 minutes',
    'It lets the web server reply "Order received!" immediately while heavy tasks (like sending emails or processing video) finish reliably in the background',
    'It deletes tasks when the server is busy',
    'It replaces the frontend website',
    'B',
    'Background queues keep web apps snappy for users while processing heavy workloads smoothly behind the scenes.',
  ],
  [
    'What does the "Shared Responsibility Model" in Cloud Computing mean?',
    'All customers share the same password',
    'The cloud provider is responsible for writing your React code',
    'The cloud provider secures the physical data centers and hardware, while YOU are responsible for securing your app code, user access rules, and secret keys',
    'Nobody is responsible for backups',
    'C',
    'Using the cloud does not mean security is automatic—you must still configure access controls and protect your application secrets.',
  ],
  [
    'What is a "Blue-Green" or "Rolling" deployment in the cloud?',
    'Changing the website theme from blue to green every Tuesday',
    'Shutting down the website for 3 days every time you fix a typo',
    'Deleting the database before updating code',
    'Updating a live application to a new version smoothly so users experience zero downtime during the release',
    'D',
    'Zero-downtime deployment strategies bring new server instances online before retiring old ones so users never see an offline page.',
  ],
  [
    'How does Cloud Computing empower students and small teams today compared to 20 years ago?',
    'A student in a college dorm can deploy a full-stack web or AI app on cloud free tiers and reach users worldwide in minutes without buying any hardware',
    'Students must buy a ₹50 lakh server room before building a website',
    'Cloud computing is only accessible to billion-dollar corporations',
    'Cloud platforms only run assembly code',
    'A',
    'Platforms like Vercel, Render, Supabase, and Google Cloud allow students to launch real production projects globally for free.',
  ],
  [
    'If you want to explore Cloud Computing hands-on, what is a great practical way to begin?',
    'Take a web or API project you built, containerize it or connect it to a cloud database (like Supabase), and deploy it live to a cloud platform with automated GitHub deployments',
    'Memorize 200 AWS service acronyms without ever deploying an app',
    'Buy a physical server rack for your bedroom',
    'Avoid using Git or Linux commands',
    'A',
    'Deploying your own projects to the cloud and seeing how environment variables, logs, and live URLs work is the best way to learn Cloud Computing.',
  ],
];

// ============================================================================
// DATABASE MANAGEMENT — Technology Exploration & Skill Discovery (Easy, Moderate, Difficult)
// ============================================================================

const dbmsEasy: RawQ[] = [
  [
    'What is the main purpose of a Database Management System (DBMS) like PostgreSQL, MySQL, or Oracle?',
    'Designing graphic illustrations and icons',
    'Organizing, storing, securing, and retrieving structured data reliably so applications and multiple users can work with it safely',
    'Cooling down computer processors',
    'Playing audio files in a web browser',
    'B',
    'A DBMS is the software engine that manages databases—keeping records organized, fast to search, and safe from corruption.',
  ],
  [
    'Why do real software applications use a Database instead of saving all user data in a single plain text file or Excel sheet?',
    'A database can handle thousands of users reading and saving data at the exact same time safely, quickly, and without overwriting each other’s changes',
    'Text files cannot store letters',
    'Excel sheets are invisible on monitors',
    'Databases do not use any disk storage',
    'A',
    'Unlike a simple file that breaks if two people save at once, a DBMS handles concurrent users, security rules, and fast searches effortlessly.',
  ],
  [
    'In a Relational Database (RDBMS), how are separate tables connected to each other (such as connecting `students` to `assessments`)?',
    'By tying a physical string between two monitors',
    'By using the exact same table name for everything',
    'By using Keys—where a `Foreign Key` (like `student_id` in `assessments`) points to the `Primary Key` (`id` in `students`)',
    'By putting all columns into a CSS file',
    'C',
    'Relational databases get their name because tables form clean relationships with one another through Primary and Foreign Keys.',
  ],
  [
    'What is a "Database Schema"?',
    'A dark-mode color theme for code editors',
    'A computer virus',
    'The speed of the internet connection',
    'The blueprint or structure of a database—defining what tables exist, what columns each table has, and what data types and rules apply',
    'D',
    'Before storing data, engineers design the schema (tables, columns, types, and relationships) like an architect’s blueprint.',
  ],
  [
    'What does "Data Redundancy" mean, and why do database designers try to avoid unnecessary duplication?',
    'Storing the exact same information repeatedly in many places, which wastes space and causes inconsistencies when that information needs to be updated',
    'Backing up your database to the cloud',
    'Having more than 10 students in a table',
    'Using clear column names',
    'A',
    'If a student’s college name is copied into 50 different rows and they update it in only one place, the database becomes inconsistent.',
  ],
  [
    'In a database table, why do we choose specific "Data Types" for columns (such as `INTEGER`, `TEXT`, `BOOLEAN`, `TIMESTAMP`)?',
    'To make the table harder to read',
    'To ensure each column stores valid information (e.g., preventing someone from saving `"hello"` inside a numerical `score` column) and to optimize storage',
    'Because a table can only have one column',
    'To change the font on the webpage',
    'B',
    'Column data types and constraints act as guardrails that keep your application’s data clean and predictable.',
  ],
  [
    'What do the basic `CRUD` operations stand for in database and backend development?',
    'Compile, Run, Undo, Debug',
    'Connect, Route, Upload, Download',
    'Create, Read, Update, and Delete (the four foundational actions performed on persistent data)',
    'Copy, Rename, Unpack, Display',
    'C',
    'Almost every feature in an app—creating an account, viewing a profile, editing details, or removing an item—maps to Create, Read, Update, or Delete.',
  ],
  [
    'What is a `NOT NULL` constraint on a database column (such as `email TEXT NOT NULL`)?',
    'A rule that forces the column to always be empty',
    'A rule that deletes the column',
    'A rule that encrypts the email',
    'A rule that guarantees a row cannot be saved if that required column is left blank/missing',
    'D',
    'Constraints like `NOT NULL` and `UNIQUE` protect data quality directly inside the database.',
  ],
  [
    'What is a `UNIQUE` constraint on the `email` column of a `students` table used for?',
    'Ensuring no two student accounts can ever be created with the exact same email address',
    'Making every email use a different font',
    'Deleting emails after 24 hours',
    'Allowing duplicate emails in every row',
    'A',
    '`UNIQUE` constraints prevent duplicate entries on fields like email addresses or usernames.',
  ],
  [
    'What is an Entity-Relationship (ER) Diagram?',
    'A chart showing internet download speeds',
    'A visual diagram that maps out database entities (like `Student`, `Assessment`, `Question`) and how they relate to one another',
    'A photo editing filter',
    'A list of CSS animations',
    'B',
    'Drawing a simple ER diagram before building an app helps you visualize what tables and relationships your project needs.',
  ],
];

const dbmsModerate: RawQ[] = [
  [
    'What is the main goal of "Database Normalization" when organizing tables?',
    'Structuring tables cleanly so each piece of data is stored in one logical place, minimizing duplicate data and update errors',
    'Putting every single column of an entire company into one giant table',
    'Deleting all foreign keys from the database',
    'Converting numbers into text strings',
    'A',
    'Normalization splits unrelated or repeating data into separate linked tables (like `students` and `assessments`) to keep data clean.',
  ],
  [
    'In database management, what is a "Transaction" (and why are the `ACID` properties important)?',
    'Paying money for a database license',
    'A group of database operations treated as a single all-or-nothing unit—so if an error or crash happens halfway through, the database safely rolls back to a valid state',
    'A way to delete backups automatically',
    'A type of CSS layout',
    'B',
    'ACID transactions guarantee that your data stays accurate and durable even if the power goes out or two users click at the same millisecond.',
  ],
  [
    'What does "Referential Integrity" guarantee between an `assessments` table and a `students` table?',
    'Every student must take 100 assessments',
    'Both tables must have the same number of columns',
    'An assessment row cannot point to a `student_id` that does not actually exist in the `students` table',
    'All scores must be 100%',
    'C',
    'Referential integrity (enforced by Foreign Keys) prevents "orphan" records that point to non-existent users.',
  ],
  [
    'How does a "Database Index" make searching a table of 1,000,000 rows fast?',
    'By deleting 990,000 rows automatically',
    'By printing the table on paper',
    'By making the font smaller',
    'By maintaining an organized lookup structure (like a B-Tree) so the database can jump straight to matching rows instead of scanning every row one by one',
    'D',
    'Without an index, the database must do a "Full Table Scan" (reading every row); with an index, lookups take milliseconds.',
  ],
  [
    'Why don’t database engineers just add an index on every single column of every table?',
    'While indexes make reading (`SELECT`) faster, every extra index takes disk space and slightly slows down writing (`INSERT`, `UPDATE`, `DELETE`) because the indexes must be updated too',
    'Databases only allow one index per year',
    'Indexes break `SELECT` queries',
    'Indexes delete primary keys',
    'A',
    'Good database design balances fast reads with efficient writes by indexing the columns that are actually searched or joined.',
  ],
  [
    'In an e-commerce or college system, how is a "Many-to-Many" relationship (e.g., one Student can join many Clubs, and one Club has many Students) stored in relational tables?',
    'By creating 50 columns named `club1, club2, ... club50` in the `students` table',
    'By creating a third linking/junction table (such as `student_clubs`) that pairs `student_id` and `club_id`',
    'Relational databases cannot store students and clubs',
    'By saving clubs in a CSS file',
    'B',
    'A junction (bridge) table cleanly connects two tables in a many-to-many relationship.',
  ],
  [
    'What is the difference between a Relational (SQL) Database (like PostgreSQL) and a Document (NoSQL) Database (like MongoDB)?',
    'SQL databases cannot run in the cloud',
    'NoSQL databases cannot store numbers',
    'Relational databases store data in structured tables with predefined schemas and joins; Document databases store flexible JSON-like documents',
    'They are identical in structure',
    'C',
    'Both are widely used: Relational databases shine when data has clear relationships and structure; Document databases fit rapidly changing unstructured data.',
  ],
  [
    'Why are automated "Database Backups" critical for any real-world application?',
    'Backups make the website colors brighter',
    'Backups replace the need for a login page',
    'Backups delete old users',
    'If hardware fails, or a developer accidentally runs a bad command, backups let you restore your data safely without losing user records',
    'D',
    'Regular automated backups (and testing that you can restore them!) are essential for protecting user data.',
  ],
  [
    'In SkillQuest, why do we store `assessments` and `assessment_scores` as separate historical records instead of overwriting a student’s row on each retake?',
    'So every attempt is preserved with its timestamp and category breakdown, allowing students to view their full Assessment History over time',
    'Because databases cannot update existing rows',
    'To make the website slower',
    'Because `UPDATE` is not a valid SQL command',
    'A',
    'Designing a schema that appends historical records (an "append-only" history log) lets applications track progress and history accurately.',
  ],
  [
    'What is "Connection Pooling" when a backend server connects to a database?',
    'Putting servers next to a swimming pool',
    'Reusing a set of open database connections efficiently across incoming web requests instead of opening and closing a brand-new connection every millisecond',
    'Combining all tables into one',
    'Sharing database passwords on social media',
    'B',
    'Connection pooling keeps database communication fast and prevents the database from getting overwhelmed under heavy traffic.',
  ],
];

const dbmsDifficult: RawQ[] = [
  [
    'When hundreds of users use an app at the exact same moment, how does a modern database (like PostgreSQL) let people read data without getting blocked by someone else saving data?',
    'By using concurrency control (such as MVCC snapshots) so readers see a consistent snapshot of the data while updates happen safely in parallel',
    'By shutting down the website whenever someone saves a form',
    'By allowing only 1 user per hour',
    'By ignoring half of the save requests',
    'A',
    'Modern databases handle concurrent reads and writes smoothly so thousands of users can use an app simultaneously.',
  ],
  [
    'How does a database ensure that a saved transaction is NEVER lost even if the server loses power a millisecond after confirming "Saved!" (Durability)?',
    'It hopes the power never goes out',
    'It immediately records the change in a fast sequential log on disk (Write-Ahead Log / WAL) so it can recover automatically on restart',
    'It emails the data to the user first',
    'It stores data only in temporary RAM',
    'B',
    'Write-Ahead Logging (WAL) is the clever mechanism that keeps relational databases resilient against sudden power failures.',
  ],
  [
    'What is "Database Replication" (having a Primary database and Read Replicas) used for in growing applications?',
    'Deleting duplicate rows',
    'Writing CSS styles automatically',
    'Keeping live copies of the database on additional servers so if the primary server fails, a replica can take over immediately (High Availability) and share read traffic',
    'Compressing images into JPEGs',
    'C',
    'Replication protects against hardware failure and helps scale applications that have millions of read requests.',
  ],
  [
    'What is a "Database Migration" in software engineering teams?',
    'Moving physical computers to another country',
    'Deleting the database every Friday',
    'Switching from Python to C++',
    'Version-controlled scripts (like `schema.sql` or migration files) that track and apply changes to database tables safely across development and production',
    'D',
    'Keeping database schema changes in versioned SQL files ensures every teammate and server has the exact same table structure.',
  ],
  [
    'When a web page feels slow because a database query is taking 5 seconds, what tool built into SQL databases helps developers see WHY the query is slow?',
    'The `EXPLAIN` (or `EXPLAIN ANALYZE`) command, which shows the query execution plan and whether an index is being used',
    'The browser zoom button',
    'A CSS validator',
    'A color picker tool',
    'A',
    '`EXPLAIN` shows you whether the database is using an index cleanly or scanning millions of rows unnecessarily.',
  ],
  [
    'In modern AI applications, what is a "Vector Database" (or PostgreSQL’s `pgvector` extension) used for?',
    'Drawing 2D SVG logos only',
    'Storing and searching AI embeddings so apps can find documents or items by semantic meaning ("Similarity Search")',
    'Replacing the CPU fan',
    'Formatting floppy disks',
    'B',
    'PostgreSQL (via `pgvector`) and specialized vector stores power modern AI search and Retrieval-Augmented Generation (RAG).',
  ],
  [
    'What is "Caching" (using an in-memory store like Redis alongside a database) used for?',
    'Deleting permanent user accounts',
    'Writing HTML code',
    'Keeping frequently requested data in ultra-fast memory so the main database does not have to recalculate the same popular query thousands of times per second',
    'Encrypting the monitor cable',
    'C',
    'Caching hot data in memory reduces database load and makes responses nearly instantaneous.',
  ],
  [
    'Why is "Data Privacy" and careful handling of Personal Identifiable Information (PII—like emails, phone numbers, and academic records) a major responsibility in Database Management?',
    'Because databases cannot store email addresses',
    'Because PII takes up too much RAM',
    'Because users do not care about privacy',
    'Because users trust applications with their personal records; encrypting data, restricting access, and collecting only necessary fields protects user trust and legal compliance',
    'D',
    'Good database management combines technical reliability with ethical stewardship of user data.',
  ],
  [
    'How does Database Management connect to Backend Development, Data Analytics, and Cloud Computing?',
    'The database is the heart of almost every application—backend APIs read/write to it, cloud platforms host it, and data analysts query it for insights',
    'Only database administrators ever touch a database',
    'Frontend websites never use data from databases',
    'Databases are only used in banking',
    'A',
    'Understanding how databases organize, relate, and secure data makes you vastly more capable across every software and data field.',
  ],
  [
    'If you want to explore Database Management further, what is a great hands-on project to try?',
    'Design a multi-table PostgreSQL database on Supabase for a real app idea (with Primary/Foreign Keys and indexes), populate it with data, and connect it to an API',
    'Only read theoretical definitions without creating any tables',
    'Store all data in a single comma-separated string column',
    'Avoid using relationships between tables',
    'A',
    'Designing a clean relational schema for your own project is the most rewarding way to master Database Management.',
  ],
];

export const DOMAIN_QUESTIONS_PART2: QuestionRecord[] = [
  ...buildCategoryQuestions('domain', 'Cybersecurity', 'cybersecurity', 'Easy', secEasy),
  ...buildCategoryQuestions('domain', 'Cybersecurity', 'cybersecurity', 'Moderate', secModerate),
  ...buildCategoryQuestions('domain', 'Cybersecurity', 'cybersecurity', 'Difficult', secDifficult),
  ...buildCategoryQuestions('domain', 'Cloud Computing', 'cloud_computing', 'Easy', cloudEasy),
  ...buildCategoryQuestions('domain', 'Cloud Computing', 'cloud_computing', 'Moderate', cloudModerate),
  ...buildCategoryQuestions('domain', 'Cloud Computing', 'cloud_computing', 'Difficult', cloudDifficult),
  ...buildCategoryQuestions('domain', 'Database Management', 'dbms', 'Easy', dbmsEasy),
  ...buildCategoryQuestions('domain', 'Database Management', 'dbms', 'Moderate', dbmsModerate),
  ...buildCategoryQuestions('domain', 'Database Management', 'dbms', 'Difficult', dbmsDifficult),
];
