import { buildCategoryQuestions, QuestionRecord, RawQ } from './programmingQuestions.ts';

// ============================================================================
// DATA ANALYTICS — Technology Exploration & Skill Discovery (Easy, Moderate, Difficult)
// ============================================================================

const daEasy: RawQ[] = [
  [
    'What is the main goal of the Data Analytics field?',
    'Designing physical computer keyboards and mice',
    'Examining datasets, spotting patterns, and turning raw numbers into clear insights for better decisions',
    'Writing operating system drivers in assembly',
    'Installing network cables in office buildings',
    'B',
    'Data Analytics focuses on collecting, cleaning, and analyzing data so organizations can understand what is happening and make informed choices.',
  ],
  [
    'A college canteen tracks daily sales of snacks for a month to see which items are most popular on Mondays vs Fridays. Which field does this represent?',
    'Data Analytics',
    'Hardware Chip Manufacturing',
    '3D Game Physics',
    'Cryptographic Password Hashing',
    'A',
    'Analyzing past sales records to find patterns and improve stock planning is a classic real-world example of Data Analytics.',
  ],
  [
    'Why is "Data Cleaning" an important first step before analyzing any dataset?',
    'It washes the physical computer screen',
    'It deletes the entire database to save disk space',
    'Real-world data often contains typos, duplicate rows, or missing values that would produce misleading results if not fixed first',
    'It changes all numbers into random letters',
    'C',
    'Analysts spend time cleaning data (fixing missing or inconsistent entries) so their charts and conclusions are accurate.',
  ],
  [
    'Which type of chart is easiest to read when you want to show how a value (like monthly website visitors) changes over time?',
    'A static text paragraph',
    'A folder directory tree',
    'A Venn diagram',
    'A Line Chart',
    'D',
    'Line charts connect data points across time intervals, making upward or downward trends easy to spot at a glance.',
  ],
  [
    'If you want to compare the number of students enrolled in 5 different college clubs side by side, which visual chart works best?',
    'A Bar Chart',
    'A scatter plot of random noise',
    'An audio waveform',
    'A network firewall log',
    'A',
    'Bar charts let viewers compare quantities across distinct categories accurately.',
  ],
  [
    'In a dataset of 10 student salaries where 9 students earn ₹40,000/month and 1 student earns ₹10,00,000/month, why is the "Median" useful alongside the "Average (Mean)"?',
    'The Median is always zero',
    'The Median gives the middle value, so it is not distorted by one extreme outlier value',
    'The Median multiplies all salaries by 10',
    'The Mean and Median are illegal to calculate together',
    'B',
    'When a dataset has extreme outliers, the median (middle value) often represents the "typical" value more realistically than the mean.',
  ],
  [
    'Which everyday tools are most commonly used by beginners and professionals in Data Analytics?',
    'Soldering irons and oscilloscopes',
    '3D modeling brushes and audio mixers',
    'Spreadsheets (Excel/Google Sheets), SQL, Python (Pandas), and dashboard tools like Power BI or Tableau',
    'BIOS bootloaders and C assembly',
    'C',
    'Data analysts combine spreadsheets, SQL queries, Python scripts, and visualization dashboards to explore and present data.',
  ],
  [
    'What is a "Dashboard" in Data Analytics?',
    'The steering wheel of a car',
    'A command-line terminal with no graphics',
    'A folder of unorganized text files',
    'A visual screen that displays key charts, trends, and summary metrics in one place for quick understanding',
    'D',
    'Analytics dashboards summarize important metrics visually so teams can track progress without reading raw tables.',
  ],
  [
    'What is the difference between Quantitative data and Qualitative (Categorical) data?',
    'Quantitative data measures numerical amounts (like score = 85); Qualitative data describes categories or labels (like learning_level = "Easy")',
    'Qualitative data only contains decimal numbers',
    'Quantitative data cannot be added or averaged',
    'Both mean the exact same thing',
    'A',
    'Recognizing whether a column is a number (quantitative) or a category label (qualitative) helps you choose the right summary and chart.',
  ],
  [
    'In a spreadsheet or database table, what does a "Missing Value" (`NULL` or blank cell) mean?',
    'The value is guaranteed to be 100',
    'No value was recorded for that specific field in that row (for example, a student left an optional survey question blank)',
    'The computer has a virus',
    'The file is encrypted',
    'B',
    'Handling missing values carefully is a core part of real-world data exploration.',
  ],
];

const daModerate: RawQ[] = [
  [
    'What is Exploratory Data Analysis (EDA)?',
    'The initial process of investigating a dataset using summary statistics and visual plots to understand its structure, patterns, and anomalies',
    'Deleting old servers from a data center',
    'Writing a mobile game in C++',
    'Designing a company logo',
    'A',
    'Before jumping to conclusions, analysts perform EDA to see what columns exist, check distributions, and spot unusual values.',
  ],
  [
    'Why do data analysts often say "Correlation does not imply Causation"?',
    'Because two variables can never move together',
    'Just because two trends move together (like ice cream sales and sunglasses sales in summer) does not mean one directly causes the other',
    'Because charts cannot show two variables',
    'Because SQL tables do not support numbers',
    'B',
    'In summer, hot weather drives both ice cream and sunglasses sales—recognizing hidden factors prevents false conclusions.',
  ],
  [
    'What is a "Pivot Table" used for in spreadsheets and data analysis?',
    'Rotating the computer monitor 90 degrees',
    'Encrypting user passwords',
    'Quickly grouping and summarizing a large table (such as calculating total or average scores by Academic Year and Division)',
    'Writing HTML tags automatically',
    'C',
    'Pivot tables let you group, count, and average thousands of rows across categories in seconds.',
  ],
  [
    'What is an "Outlier" in a dataset?',
    'The most common value in a column',
    'The name of the first column in a table',
    'A chart title',
    'A data point that is unusually far away from the rest of the values (such as a human age recorded as `250`)',
    'D',
    'Spotting outliers helps analysts catch data-entry mistakes or investigate unusual real-world events.',
  ],
  [
    'If a streaming app notices that 10,000 users opened the app, 6,000 searched for a video, and 3,000 pressed play, what type of analysis is this?',
    'Funnel Analysis (tracking step-by-step progression to see where users drop off)',
    'Hardware circuit analysis',
    'Operating system kernel debugging',
    'Font color styling',
    'A',
    'Funnel analysis helps product and data teams see which step of a user journey needs improvement.',
  ],
  [
    'What is a KPI (Key Performance Indicator)?',
    'A keyboard shortcut for pasting text',
    'A measurable metric used to track progress toward an important goal (such as "Monthly Active Students" or "Course Completion Rate")',
    'A type of database error',
    'A Python syntax error',
    'B',
    'KPIs help organizations focus on the metrics that actually matter rather than getting lost in hundreds of random numbers.',
  ],
  [
    'Which chart type is designed to show whether two numerical variables (such as "Hours Practiced" and "Assessment Score") have a relationship?',
    'A Pie Chart',
    'A Folder Icon',
    'A Scatter Plot',
    'A Navigation Bar',
    'C',
    'A scatter plot places one variable on the X-axis and the other on the Y-axis, making trends or clusters easy to see.',
  ],
  [
    'Why is a Pie Chart usually hard to read if a category has 15 different slices of similar size?',
    'Pie charts cannot use colors',
    'Computers cannot draw circles',
    'Pie charts only work for negative numbers',
    'Human eyes compare bar lengths much more accurately than tiny slice angles',
    'D',
    'Data visualization best practices recommend using a Bar Chart when comparing more than 4–5 categories.',
  ],
  [
    'When combining data from a `csv` file of student names and a database table of assessment scores, what must both sources share?',
    'A common identifier (such as `student_id` or `email`) so rows can be matched accurately',
    'The exact same file size in bytes',
    'The same font style',
    'The same creation timestamp',
    'A',
    'Joining or merging datasets relies on a shared key column that links records across sources.',
  ],
  [
    'How does Data Analytics help a hospital or healthcare clinic in the real world?',
    'By replacing doctors with HTML files',
    'By analyzing patient appointment wait times, seasonal illness trends, and medicine inventory so the clinic can plan better',
    'By manufacturing X-ray machines',
    'By changing the hospital paint color',
    'B',
    'Every industry—healthcare, education, sports, finance, and tech—uses Data Analytics to improve operations and outcomes.',
  ],
];

const daDifficult: RawQ[] = [
  [
    'An education platform wants to test whether a new dashboard layout helps students find assessments faster. How do they test this with data?',
    'By running an A/B Test (showing Version A to one group and Version B to another group and comparing completion rates)',
    'By guessing without looking at any numbers',
    'By deleting the website for a week',
    'By asking only one developer’s opinion',
    'A',
    'A/B testing uses real data from two groups to see whether a change genuinely improves user experience.',
  ],
  [
    'Suppose a campus survey about college Wi-Fi quality only collects responses from students inside the computer lab who already have wired internet. What problem does this dataset have?',
    'Too many columns',
    'Sampling Bias (the sample does not fairly represent students trying to use Wi-Fi in hostels or classrooms)',
    'The file format is too modern',
    'The numbers are too small',
    'B',
    'Good data analysts always ask how the data was collected so biased samples do not lead to flawed conclusions.',
  ],
  [
    'What is "Cohort Analysis" used for when studying user or student progress over time?',
    'Sorting names by last letter',
    'Deleting old database backups',
    'Grouping people who started in the same time period (e.g., "FY Batch of 2026") to track how their engagement or scores evolve over months',
    'Checking CPU temperature',
    'C',
    'Cohort analysis compares groups over their lifecycle rather than mixing brand-new users with long-time users.',
  ],
  [
    'When analyzing daily ice cream sales across an entire year, you notice sales rise every weekend and peak every May. What is this repeating pattern called?',
    'A syntax error',
    'Data corruption',
    'A database deadlock',
    'Seasonality (regular, predictable periodic fluctuations over time)',
    'D',
    'Understanding seasonality prevents analysts from mistaking normal seasonal cycles for sudden business problems.',
  ],
  [
    'Why is it helpful to look at data broken down by subgroups (e.g., by Academic Year) instead of only looking at one combined overall average?',
    'Because an overall average can hide important differences or opposite trends happening inside individual groups',
    'Because overall averages cannot be calculated by computers',
    'Because subgroups always have 100% scores',
    'Because SQL does not allow overall averages',
    'A',
    'Segmenting data by meaningful categories often reveals insights that a single blended number hides.',
  ],
  [
    'What is an ETL pipeline (Extract, Transform, Load) in data workflows?',
    'A physical water pipe in a server room',
    'An automated process that collects raw data from sources (Extract), cleans and formats it (Transform), and saves it into an analytics database (Load)',
    'A CSS animation property',
    'A keyboard shortcut in Excel',
    'B',
    'ETL pipelines automate moving and cleaning data so dashboards stay up to date every day.',
  ],
  [
    'When presenting data findings to non-technical teammates or college faculty, what makes "Data Storytelling" effective?',
    'Showing 50,000 raw unformatted spreadsheet rows on a projector',
    'Using as much confusing jargon as possible',
    'Combining clear, labeled visuals with a simple explanation of what the trend means and what action can be taken next',
    'Hiding the axis labels on all charts',
    'C',
    'The best data analysts don’t just calculate numbers—they communicate insights clearly so others can understand and act on them.',
  ],
  [
    'How does Descriptive Analytics ("What happened?") differ from Diagnostic Analytics ("Why did it happen?")?',
    'They are both types of computer hardware',
    'Descriptive analytics deletes data; Diagnostic analytics creates data',
    'Neither uses charts or numbers',
    'Descriptive summarizes past metrics (e.g., "Scores dropped 10%"), while Diagnostic investigates the root causes behind that change',
    'D',
    'Analytics progresses from seeing *what* happened to understanding *why* it happened and *what* to improve next.',
  ],
  [
    'If you enjoy curiosity, spotting patterns in numbers, creating clear charts, and answering real-world questions with evidence, how can you explore Data Analytics further?',
    'Download a public dataset on a topic you care about (sports, movies, education), explore it with SQL or Python Pandas, and build a visual dashboard',
    'Memorize textbook definitions without ever opening a dataset',
    'Write a hardware device driver in assembly',
    'Avoid using spreadsheets or charts',
    'A',
    'Exploring a real dataset on a topic you find interesting is the fastest way to see if Data Analytics excites you.',
  ],
  [
    'How do Data Analytics and Data Science & AI complement each other in a technology organization?',
    'They cannot work together',
    'Data Analytics focuses on understanding historical patterns and guiding decisions, while Data Science & AI builds predictive and automated models on top of data',
    'Data Analytics is only for hardware; Data Science is only for CSS',
    'Both only design company logos',
    'B',
    'Strong data analytics foundations are valuable on their own and also serve as a natural stepping stone into Data Science & AI.',
  ],
];

// ============================================================================
// DATA SCIENCE & AI — Technology Exploration & Skill Discovery (Easy, Moderate, Difficult)
// ============================================================================

const dsEasy: RawQ[] = [
  [
    'In simple terms, what is Machine Learning (a core part of Data Science & AI)?',
    'Teaching computers to learn patterns from data and make predictions or decisions without writing hard-coded rules for every single case',
    'Physically building robot arms out of metal',
    'Typing faster on a mechanical keyboard',
    'Installing updates on a smartphone',
    'A',
    'Instead of programming thousands of manual `if-else` rules, Machine Learning lets an algorithm learn patterns directly from examples.',
  ],
  [
    'Which of these everyday features is powered by Artificial Intelligence and Machine Learning?',
    'A basic calculator adding `2 + 2`',
    'Email spam filters, YouTube/Netflix recommendations, voice assistants, and face unlock on phones',
    'A static HTML heading on a page',
    'A USB flash drive storing a PDF',
    'B',
    'Recommendation engines, spam detection, speech recognition, and computer vision are everyday applications of AI.',
  ],
  [
    'What is "Supervised Learning" in machine learning?',
    'When a teacher sits next to the computer monitor',
    'When a computer runs without electricity',
    'Training a model using labeled examples where the correct answer is already known (such as past houses with their actual sale prices)',
    'Deleting all labels from a database',
    'C',
    'In Supervised Learning, the model learns by comparing its predictions against known correct answers ("labels") during training.',
  ],
  [
    'What is "Unsupervised Learning" used for?',
    'Predicting exact exam marks from labeled answer sheets',
    'Formatting hard drives',
    'Writing CSS stylesheets',
    'Discovering hidden groups or clusters in unlabeled data (such as grouping shoppers with similar buying habits)',
    'D',
    'Unsupervised Learning finds natural groupings (clustering) or patterns in data when no pre-existing labels are provided.',
  ],
  [
    'Suppose a model predicts whether an incoming email is `"Spam"` or `"Not Spam"`. What kind of problem is this?',
    'A Classification problem (predicting a category label)',
    'A hardware cooling problem',
    'A network cabling problem',
    'A font styling problem',
    'A',
    'Classification predicts discrete categories (`Spam` vs `Not Spam`, `Cat` vs `Dog`), whereas Regression predicts continuous numbers.',
  ],
  [
    'Suppose a model predicts the continuous numerical price of a used car (e.g., `₹4,25,000`) based on its age and mileage. What kind of problem is this?',
    'Clustering',
    'A Regression problem (predicting a continuous numerical value)',
    'Database normalization',
    'HTML rendering',
    'B',
    'When the output to predict is a continuous number (like price, temperature, or score), it is a Regression task.',
  ],
  [
    'In a machine learning dataset for predicting student exam scores, what are the input columns (like `study_hours`, `attendance`) vs the output column (`exam_score`) called?',
    'Bugs and Errors',
    'Rows and Borders',
    'Features (inputs) and Target / Label (the output to predict)',
    'Headers and Footers',
    'C',
    'Models use input "Features" to learn how to predict the output "Target" (or label).',
  ],
  [
    'Why do data scientists split their data into a "Training Set" and a "Test Set"?',
    'To delete half the data permanently',
    'Because computers can only read small files',
    'To make the code longer',
    'So the model can learn patterns on the Training Set and then be fairly evaluated on unseen data in the Test Set',
    'D',
    'Just like a teacher tests students with new questions rather than the exact practice sheet they memorized, a Test Set checks if the model truly generalizes.',
  ],
  [
    'What branch of AI focuses on helping computers understand, translate, and generate human language (like chatbots and translators)?',
    'Natural Language Processing (NLP)',
    'Computer Hardware Soldering',
    'Relational Table Indexing',
    'CSS Grid Layout',
    'A',
    'Natural Language Processing (NLP) powers translation tools, sentiment analysis, and Large Language Models (LLMs).',
  ],
  [
    'What branch of AI enables computers to recognize objects in photos, read handwritten text, or detect obstacles for self-driving cars?',
    'Audio Mixing',
    'Computer Vision',
    'Spreadsheet Accounting',
    'Network Routing',
    'B',
    'Computer Vision teaches machines to interpret and understand visual information from images and videos.',
  ],
];

const dsModerate: RawQ[] = [
  [
    'What does "Overfitting" mean when training a machine learning model?',
    'The model memorizes noise and exact details of the training data, scoring great on training data but poorly on new, unseen test data',
    'The model file is too large to fit on a monitor',
    'The computer has too much RAM installed',
    'The model trains too quickly',
    'A',
    'A good model learns general patterns rather than memorizing the training set word-for-word.',
  ],
  [
    'What is "Underfitting" in machine learning?',
    'When a model is so complex that it memorizes every row',
    'When a model is too simple to capture the basic pattern in the data, performing poorly on both training and test data',
    'When the dataset has too many clean rows',
    'When the model achieves 100% accuracy',
    'B',
    'Underfitting happens when a model is too simplistic to learn the underlying trend.',
  ],
  [
    'What is "Feature Engineering" in a Data Science project?',
    'Building physical server racks',
    'Designing website buttons',
    'Selecting, transforming, and creating meaningful input variables from raw data so a model can learn more effectively',
    'Installing an operating system',
    'C',
    'Creating helpful features (like extracting "Day of Week" from a raw timestamp) often improves model accuracy more than changing algorithms.',
  ],
  [
    'Why can "Accuracy" alone be misleading if 99% of bank transactions are normal and only 1% are fraud?',
    'Because accuracy cannot be calculated with percentages',
    'Because banks do not use computers',
    'Because fraud is impossible to detect',
    'A model that blindly guesses "Normal" every single time gets 99% accuracy while catching 0% of actual fraud!',
    'D',
    'For imbalanced datasets, data scientists look at Precision and Recall to verify how well the rare class is actually detected.',
  ],
  [
    'How does a "Decision Tree" model make predictions?',
    'By asking a sequence of simple yes/no questions about the features (like a flowchart) until it reaches a prediction leaf',
    'By planting real trees outside the data center',
    'By sorting files alphabetically on disk',
    'By encrypting data with a password',
    'A',
    'Decision Trees are intuitive models that split data step-by-step based on feature thresholds.',
  ],
  [
    'What is the idea behind a "Random Forest" in machine learning?',
    'Training a single tiny rule',
    'Combining the predictions of many different Decision Trees ("wisdom of the crowd") to get a more accurate and stable result',
    'Generating random numbers with no data',
    'Deleting random tables from a database',
    'B',
    'Ensemble models like Random Forests combine multiple trees so individual mistakes cancel out.',
  ],
  [
    'In Unsupervised Learning, what is the `K-Means` algorithm commonly used for?',
    'Translating English to Spanish',
    'Writing SQL JOIN queries',
    'Grouping unlabeled data points into `K` clusters based on how similar they are to one another',
    'Designing HTML forms',
    'C',
    'K-Means groups similar items together—such as clustering customers by shopping behavior or articles by topic.',
  ],
  [
    'Since machine learning algorithms work with numbers, what must be done if a dataset column contains text categories like `"FY"`, `"SY"`, `"TY"`?',
    'Delete the entire dataset',
    'Print the dataset on paper',
    'Rename the file to `.jpg`',
    'Encode the categories into numerical representations (such as One-Hot Encoding or ordinal numbers) before training',
    'D',
    'Encoding turns categorical text labels into numerical columns that mathematical models can process.',
  ],
  [
    'Which Python library is the industry standard for classical machine learning algorithms (like regression, classification, and clustering)?',
    'scikit-learn',
    'Bootstrap CSS',
    'jQuery',
    'Express.js',
    'A',
    '`scikit-learn` provides a clean, consistent interface (`fit`, `predict`, `score`) for dozens of foundational ML algorithms.',
  ],
  [
    'What is the typical step-by-step workflow of a real-world Data Science project?',
    'Deploy model -> Delete data -> Understand problem',
    'Understand the problem -> Collect & clean data -> Explore features -> Train & evaluate models -> Deploy & monitor',
    'Write CSS -> Buy server -> Skip testing',
    'Train model without looking at the data first',
    'B',
    'Data Science is a structured lifecycle that starts with understanding the problem and preparing clean data before training models.',
  ],
];

const dsDifficult: RawQ[] = [
  [
    'What is a "Neural Network" (and "Deep Learning") inspired by, and where does it excel?',
    'Layered networks of artificial nodes that excel at complex unstructured data like images, audio, and natural language text',
    'A simple 2-column spreadsheet formula',
    'A network cable connecting two printers',
    'A relational database foreign key',
    'A',
    'Deep Learning stacks multiple layers of artificial neurons to automatically learn rich representations from images, speech, and text.',
  ],
  [
    'How do Recommendation Systems (like those on Spotify, YouTube, or Amazon) suggest items you might like?',
    'By picking items completely at random',
    'By analyzing past interaction patterns—either finding users with similar tastes (Collaborative Filtering) or matching item attributes (Content-Based)',
    'By asking a human employee to manually pick songs for every user',
    'By checking your computer’s screen brightness',
    'B',
    'Recommendation engines combine user behavior patterns and item features to personalize discovery.',
  ],
  [
    'What are Large Language Models (LLMs) fundamentally trained to do during their initial pre-training phase?',
    'Manage physical cloud server racks',
    'Defragment hard drives',
    'Learn language patterns, grammar, and world knowledge by predicting the next token (word/sub-word) across massive text datasets',
    'Replace operating system kernels',
    'C',
    'By learning to predict context and tokens across vast text corpora (using the Transformer architecture), LLMs develop broad language capabilities.',
  ],
  [
    'In AI and Natural Language Processing, what is an "Embedding"?',
    'Plugging a USB drive into a laptop',
    'Adding an `<img>` tag to HTML',
    'A database backup file',
    'Representing words, sentences, or images as numerical vectors so items with similar meanings are placed close together mathematically',
    'D',
    'Embeddings allow AI systems to search by meaning (semantic search) rather than only matching exact keywords.',
  ],
  [
    'Why is "Responsible AI" and checking for "Dataset Bias" critical when building AI systems for healthcare, hiring, or finance?',
    'If historical training data contains unfair human biases or underrepresents certain groups, the AI model can learn and repeat those unfair patterns',
    'AI models never make any mistakes',
    'Bias only affects the font color of the app',
    'Dataset quality does not affect model predictions',
    'A',
    'Fair, trustworthy AI requires auditing training data, testing performance across diverse groups, and keeping humans in the loop.',
  ],
  [
    'What is "Transfer Learning" or "Fine-Tuning" in modern AI development?',
    'Moving a computer from one desk to another',
    'Starting with a powerful pre-trained model and adapting it to a specific task (rather than training from scratch for millions of dollars)',
    'Deleting a trained model after one use',
    'Converting Python code into C',
    'B',
    'Transfer learning lets students and teams build high-accuracy vision or language apps using pre-trained foundation models.',
  ],
  [
    'Once a machine learning model is trained, how do other web or mobile apps usually use its predictions in production?',
    'Users must install Jupyter Notebook on their phone',
    'The model is printed on paper',
    'The trained model is wrapped inside a backend API (e.g., using FastAPI) that receives input data and returns predictions as JSON',
    'The model runs inside a CSS file',
    'C',
    'Deploying a model behind a web API allows any frontend or mobile application to request real-time predictions.',
  ],
  [
    'What happens if real-world user behavior changes significantly months after an ML model was deployed ("Data Drift")?',
    'The model automatically rewrites its own database schema',
    'The server hardware melts',
    'Nothing—models stay 100% accurate forever',
    'The model’s accuracy can gradually degrade, so teams monitor predictions and retrain the model with fresh data',
    'D',
    'Real-world patterns evolve over time, so monitoring and updating models is an ongoing part of Data Science & AI.',
  ],
  [
    'When solving a simple problem (like calculating a student’s percentage score from correct answers), should you use a complex Deep Learning model?',
    'No—when a clear mathematical formula or simple rule solves the problem 100% accurately, a complex AI model is unnecessary',
    'Yes, every single line of software should be a 100-layer neural network',
    'Yes, simple addition requires a GPU cluster',
    'Only AI can divide two numbers',
    'A',
    'Good engineers know *when* AI is needed (complex pattern recognition) and when simple, deterministic code or analytics is better.',
  ],
  [
    'If you are excited to explore Data Science & AI further, what is a great beginner-friendly project to try?',
    'Train a simple classification or regression model on a clean dataset using Python and `scikit-learn`, and visualize its predictions',
    'Attempt to build a 10,000-GPU data center at home first',
    'Only watch sci-fi movies without learning Python or data basics',
    'Skip learning how data tables and charts work',
    'A',
    'Starting with Python, Pandas, and `scikit-learn` on a small real-world dataset builds a rock-solid foundation for AI.',
  ],
];

// ============================================================================
// WEB DEVELOPMENT — Technology Exploration & Skill Discovery (Easy, Moderate, Difficult)
// ============================================================================

const webEasy: RawQ[] = [
  [
    'In Web Development, what is the difference between the "Frontend" and the "Backend"?',
    'The Frontend is the visual interface users see and interact with in their browser; the Backend is the server and database working behind the scenes',
    'The Frontend is the computer monitor; the Backend is the power cord',
    'They are two names for the exact same CSS file',
    'Frontend only works offline; Backend only works on phones',
    'A',
    'Frontend development focuses on user experience in the browser, while Backend development handles business logic, security, and data storage.',
  ],
  [
    'What is the main role of HTML (HyperText Markup Language) on a webpage?',
    'Connecting to a cloud database',
    'Defining the structure and content of the page—such as headings, paragraphs, links, images, and forms',
    'Encrypting user passwords',
    'Running machine learning models',
    'B',
    'HTML provides the semantic building blocks (`<h1>`, `<p>`, `<nav>`, `<button>`) of every webpage.',
  ],
  [
    'What is the main role of CSS (Cascading Style Sheets) in web development?',
    'Storing user rows in a SQL table',
    'Managing server CPU threads',
    'Controlling the visual appearance, colors, fonts, spacing, and responsive layout of HTML elements',
    'Sending automated emails',
    'C',
    'CSS transforms plain HTML structure into a polished, visually appealing interface across desktop and mobile screens.',
  ],
  [
    'What does "Responsive Web Design" mean?',
    'A website that replies to emails automatically',
    'A website that only opens on 27-inch desktop monitors',
    'A website with no images',
    'Designing a website so its layout adapts smoothly and looks great on phones, tablets, and desktop screens alike',
    'D',
    'Because people browse the web on devices of all sizes, responsive layouts (using Flexbox, Grid, and media queries) are essential.',
  ],
  [
    'When you type a website address (URL) into your browser, what protocol do the browser and web server use to communicate?',
    'HTTP / HTTPS (HyperText Transfer Protocol)',
    'HDMI',
    'Bluetooth Audio',
    'USB 3.0',
    'A',
    'Browsers send HTTP/HTTPS requests to web servers, which respond with HTML, CSS, JavaScript, images, or JSON data.',
  ],
  [
    'What does the well-known HTTP status code `404 Not Found` mean when browsing the web?',
    'The internet was deleted globally',
    'The server is reachable, but the specific page or resource you requested does not exist at that URL',
    'Your computer battery is at 4%',
    'The page loaded with 100% success',
    'B',
    'HTTP status codes communicate request outcomes: `200 OK` means success, `404 Not Found` means a missing URL, and `500` means a server error.',
  ],
  [
    'Why is it helpful to use semantic HTML tags like `<header>`, `<nav>`, `<main>`, and `<footer>` instead of only using generic `<div>` tags?',
    'They make the internet connection faster',
    'They replace the need for JavaScript',
    'They make the page structure clear for developers, search engines, and screen readers used by visually impaired users',
    'They automatically create a database',
    'C',
    'Semantic HTML improves accessibility and readability by clearly describing what role each section of the page plays.',
  ],
  [
    'What is a "Full-Stack Web Developer"?',
    'Someone who stacks physical laptops on a desk',
    'Someone who only edits photos',
    'Someone who only writes documentation',
    'A developer who can build both the user-facing Frontend and the server/database Backend of a web application',
    'D',
    'Full-stack developers understand how the browser interface, backend API, and database all fit together end-to-end.',
  ],
  [
    'Why should every meaningful `<img>` tag on a website include a descriptive `alt` attribute?',
    'So screen readers can describe the image to visually impaired users, and fallback text appears if the image fails to load',
    'To make the image file 10 times larger',
    'Because browsers block images without `alt`',
    'To convert the image into a video',
    'A',
    'Web accessibility ensures everyone can use the web effectively.',
  ],
  [
    'What are the Browser Developer Tools (opened with F12 or Inspect) used for?',
    'Playing 3D DVD movies',
    'Inspecting HTML/CSS live on a page, checking the JavaScript console for errors, and viewing network API requests',
    'Formatting the computer hard drive',
    'Cooling down the laptop fan',
    'B',
    'Browser DevTools are a web developer’s best friend for experimenting with styles and debugging code in real time.',
  ],
];

const webModerate: RawQ[] = [
  [
    'In a modern web application (like SkillQuest), what is the role of a REST API?',
    'Allowing the frontend browser app and the backend server to exchange structured data (usually in JSON format) over HTTP routes like `/api/questions`',
    'Putting the computer into sleep mode to rest',
    'Styling CSS buttons with rounded corners',
    'Replacing the monitor cable',
    'A',
    'An API (Application Programming Interface) acts as the messenger between the frontend UI and the backend server/database.',
  ],
  [
    'What is the basic difference between an HTTP `GET` request and an HTTP `POST` request?',
    '`GET` deletes data; `POST` turns off the server',
    '`GET` is used to retrieve/read data from a server; `POST` is used to send/submit new data (like a login form or assessment submission) to the server',
    'Both are only used for styling fonts',
    '`POST` can only be used without the internet',
    'B',
    'Web APIs use `GET` for reading resources and `POST` (or `PUT`/`PATCH`) when submitting or updating data.',
  ],
  [
    'Why do modern web developers use component-based frameworks like React?',
    'Because HTML is no longer supported by Chrome',
    'To write SQL queries inside CSS files',
    'To break complex user interfaces into modular, reusable pieces (components) that automatically update when their data changes',
    'To slow down website loading',
    'C',
    'Component-based architecture lets you build a `Button` or `AssessmentCard` once and reuse it cleanly across the entire app.',
  ],
  [
    'What is the difference between CSS `Flexbox` and CSS `Grid` when laying out a webpage?',
    'Flexbox is only for colors; Grid is only for fonts',
    'Neither works on mobile phones',
    'Both require a backend database to work',
    'Flexbox is great for aligning items in a single row or column; Grid is great for two-dimensional multi-row and multi-column layouts',
    'D',
    'Flexbox and CSS Grid work together to make modern responsive page layouts clean and flexible.',
  ],
  [
    'When a user fills out a Sign-Up form on a website, why should input validation happen on BOTH the frontend and the backend?',
    'Frontend validation gives the user instant helpful feedback, while Backend validation guarantees security and data integrity even if someone bypasses the browser',
    'Validation is only needed to make code longer',
    'Frontend validation replaces the need for a database',
    'Backend servers cannot check if an email is empty',
    'A',
    'Frontend checks provide a smooth user experience, and backend checks enforce strict security rules.',
  ],
  [
    'After a student logs into a web application, how does the app remember they are signed in as they move from page to page?',
    'The student must re-type their password on every single click',
    'By using an authentication session token or cookie that is sent with requests to verify the user’s identity',
    'By changing the monitor resolution',
    'By saving their password in the page title',
    'B',
    'Session tokens (or secure cookies) allow authenticated users to navigate protected pages seamlessly.',
  ],
  [
    'What is "Client-Side Routing" (such as using React Router in a web app)?',
    'Configuring physical Wi-Fi routers in a building',
    'Restarting the browser on every click',
    'Switching between different pages/views (like `/dashboard`, `/assessment`, `/history`) smoothly in the browser without a full page reload',
    'Deleting browser history',
    'C',
    'Client-side routing makes multi-page web applications feel fast and seamless.',
  ],
  [
    'What is a utility-first CSS framework like `Tailwind CSS` used for?',
    'Writing backend database queries',
    'Training machine learning models',
    'Compiling C++ files',
    'Styling components rapidly and consistently directly in your markup using composable classes like `flex`, `p-6`, `rounded-xl`, and `text-white`',
    'D',
    'Tailwind CSS speeds up frontend styling while keeping spacing, colors, and responsive breakpoints consistent.',
  ],
  [
    'What does HTTP status code `401 Unauthorized` mean when a frontend app calls a backend API?',
    'The request requires valid user authentication (for example, the user is not logged in or their session token is missing/expired)',
    'The website was deleted permanently',
    'The request succeeded with zero issues',
    'The CSS file has a typo',
    'A',
    '`401` signals that the user needs to sign in before accessing that protected API endpoint.',
  ],
  [
    'Why do web developers use `Git` and `GitHub` when building web applications?',
    'To host SQL databases directly inside CSS',
    'To track code changes over time (version control), experiment safely on branches, and collaborate with teammates without overwriting each other’s work',
    'To replace the web browser',
    'To increase laptop screen brightness',
    'B',
    'Version control with Git lets you save checkpoints of your project, revert mistakes, and collaborate smoothly.',
  ],
];

const webDifficult: RawQ[] = [
  [
    'When deploying a full-stack web application to the internet, what is the role of `.env` (Environment Variables) on the server?',
    'Keeping sensitive configuration (like database URLs and secret API keys) outside of source code so secrets are never exposed publicly',
    'Making the website font larger',
    'Replacing HTML tags',
    'Drawing SVG icons',
    'A',
    'Environment variables let you configure secrets securely per environment (local development vs production server).',
  ],
  [
    'Why is Web Performance (how fast a page loads and responds to clicks) so important in real-world web development?',
    'Fast websites use more battery',
    'Slow-loading pages frustrate users—especially on mobile networks—and hurt both user experience and search engine rankings',
    'Browsers refuse to open pages that load in under 10 seconds',
    'Performance only matters on gaming PCs',
    'B',
    'Optimizing image sizes, minimizing unnecessary downloads, and writing clean code keeps web apps fast for every user.',
  ],
  [
    'What is CORS (Cross-Origin Resource Sharing) in web browsers?',
    'A CSS layout property',
    'A database backup tool',
    'A browser security feature that controls whether a website on one domain is allowed to request data from an API on a different domain',
    'A Python library for charts',
    'C',
    'Browsers enforce CORS rules so random untrusted websites cannot secretly read your data from another website’s API.',
  ],
  [
    'How do modern deployment platforms (like Vercel, Render, or Cloud Run) make sharing web projects easier for students and teams?',
    'They require buying physical server racks first',
    'They only work on local Wi-Fi',
    'They delete your code after 5 minutes',
    'They automatically build your project from code and host it on a live HTTPS URL with global content delivery',
    'D',
    'Modern cloud deployment platforms let you take a web project from your laptop to a live shareable HTTPS link in minutes.',
  ],
  [
    'What is the difference between a Static Website and a Dynamic Full-Stack Web Application?',
    'A Static Website displays the same pre-built pages to everyone; a Dynamic Web App interacts with a backend and database to show personalized user data (like your profile and assessment history)',
    'Static websites cannot use CSS',
    'Dynamic websites cannot use HTML',
    'They are identical',
    'A',
    'A portfolio brochure site is often static, while an interactive platform with user accounts and saved scores is a dynamic full-stack application.',
  ],
  [
    'When an application needs instant live updates—such as a live multiplayer quiz or real-time chat—what technology is commonly used alongside standard HTTP?',
    'Floppy disks',
    'WebSockets (which keep a two-way real-time connection open between the browser and server)',
    'Static PDF files',
    'Print stylesheets',
    'B',
    'WebSockets allow the server to push live updates to connected browsers immediately without waiting for the user to refresh.',
  ],
  [
    'What does "Search Engine Optimization" (SEO) mean when building a public website?',
    'Encrypting the website so search engines cannot find it',
    'Paying users to click buttons',
    'Structuring pages with clear titles, meta descriptions, semantic headings, and fast loading so search engines can understand and index the site accurately',
    'Writing all code in C++',
    'C',
    'Good HTML structure, `<title>` tags, and `<meta name="description">` tags help people discover your website through search engines and social previews.',
  ],
  [
    'In a well-designed web app, why is "Loading State" and "Error Handling" important when fetching data from an API?',
    'So the screen goes completely blank forever',
    'To make the server work harder',
    'Because APIs always fail',
    'So the user clearly sees a loading indicator while data is being fetched, and gets a helpful retry message if the connection drops',
    'D',
    'Thoughtful loading spinners and friendly error messages make a web application feel reliable and user-friendly.',
  ],
  [
    'How does Web Development connect with other technology domains like Cybersecurity, Database Management, and AI?',
    'Web applications often serve as the user-facing doorway that connects secure authentication (Cybersecurity), data storage (Databases), and smart features (AI)',
    'Web Development is completely isolated from all other tech fields',
    'Web developers never use databases or security',
    'AI replaces the need for user interfaces',
    'A',
    'Almost every modern software product—whether in AI, fintech, or healthcare—needs a clean, secure web interface for people to use it.',
  ],
  [
    'If you enjoy designing interfaces, building interactive features, and seeing your creations come alive on a shareable link, how can you explore Web Development further?',
    'Build and deploy a complete project—start with HTML/CSS/JS, learn React for frontend UI, and connect it to a Node/Express + Supabase backend',
    'Only read about HTML tags without building a page',
    'Avoid using browser developer tools',
    'Wait until you memorize every CSS property by heart',
    'A',
    'Web Development rewards learning by doing—every small webpage or full-stack app you build teaches you practical skills you can showcase.',
  ],
];

export const DOMAIN_QUESTIONS_PART1: QuestionRecord[] = [
  ...buildCategoryQuestions('domain', 'Data Analytics', 'data_analytics', 'Easy', daEasy),
  ...buildCategoryQuestions('domain', 'Data Analytics', 'data_analytics', 'Moderate', daModerate),
  ...buildCategoryQuestions('domain', 'Data Analytics', 'data_analytics', 'Difficult', daDifficult),
  ...buildCategoryQuestions('domain', 'Data Science & AI', 'data_science_ai', 'Easy', dsEasy),
  ...buildCategoryQuestions('domain', 'Data Science & AI', 'data_science_ai', 'Moderate', dsModerate),
  ...buildCategoryQuestions('domain', 'Data Science & AI', 'data_science_ai', 'Difficult', dsDifficult),
  ...buildCategoryQuestions('domain', 'Web Development', 'web_dev', 'Easy', webEasy),
  ...buildCategoryQuestions('domain', 'Web Development', 'web_dev', 'Moderate', webModerate),
  ...buildCategoryQuestions('domain', 'Web Development', 'web_dev', 'Difficult', webDifficult),
];
