import { buildCategoryQuestions, QuestionRecord, RawQ } from './programmingQuestions.ts';

// ============================================================================
// JAVA — Technology Exploration & Skill Discovery Questions (Easy, Moderate, Difficult)
// ============================================================================

const javaEasy: RawQ[] = [
  [
    'Which type of applications can commonly be developed using the Java programming language?',
    'Enterprise backend systems, Android mobile apps, banking software, and large-scale web services',
    'Only simple CSS stylesheets for blog fonts',
    'Physical computer monitor screens',
    'Only Apple iOS-exclusive Swift storyboards',
    'A',
    'Java is widely used across banking, e-commerce backends, enterprise software, and Android app development.',
  ],
  [
    'What does Java’s famous slogan "Write Once, Run Anywhere" mean for developers?',
    'You only need to write one line of code for any program',
    'Compiled Java code (bytecode) can run on Windows, macOS, or Linux without rewriting it for each operating system',
    'A Java program can only be run one time before it expires',
    'Java code runs without electricity',
    'B',
    'Java compiles into platform-independent bytecode that runs on the Java Virtual Machine (JVM) on any device.',
  ],
  [
    'What is the role of the JVM (Java Virtual Machine)?',
    'It is a physical laptop sold in stores',
    'It is an image editing tool for logos',
    'It executes compiled Java bytecode on your specific computer or server',
    'It replaces your internet router',
    'C',
    'The JVM acts as a bridge between compiled Java bytecode and the underlying operating system.',
  ],
  [
    'Java is strongly centered around which style of programming?',
    'Spreadsheet-only programming',
    'Hardware soldering programming',
    'Color-based styling',
    'Object-Oriented Programming (organizing code around classes and objects)',
    'D',
    'In Java, programs are structured around classes and objects that model real-world entities cleanly.',
  ],
  [
    'In Java, what is the relationship between a `Class` and an `Object`?',
    'A Class is a blueprint (like a Student template), and an Object is an actual instance created from that blueprint',
    'An Object is a file folder, and a Class is a monitor',
    'They mean the exact opposite of variables',
    'Java does not use classes or objects',
    'A',
    'You define a `class` once (e.g., `class Car`) and create multiple `objects` from it (`myCar`, `yourCar`).',
  ],
  [
    'How does Java handle cleaning up memory for objects that a program is no longer using?',
    'The user must restart their computer every 10 minutes',
    'Java has an automatic Garbage Collector that frees unused memory in the background',
    'Memory can never be reused in Java',
    'Developers must physically unplug RAM sticks',
    'B',
    'Automatic Garbage Collection makes Java safer and less error-prone than manually freeing every piece of memory.',
  ],
  [
    'Which standard Java statement is used to print a line of text to the console?',
    'console.print("Hello");',
    'echo("Hello");',
    'System.out.println("Hello");',
    'display.text("Hello");',
    'C',
    '`System.out.println()` prints text to the standard output console followed by a new line.',
  ],
  [
    'Why do large organizations like banks, airlines, and insurance companies rely heavily on Java?',
    'Because Java has no security features',
    'Because Java only works on small calculators',
    'Because Java files are smaller than 1 byte',
    'Because Java is stable, strongly typed, secure, and scales reliably for large teams and long-term systems',
    'D',
    'Java’s strict type checking, mature ecosystem, and reliability make it a top choice for mission-critical enterprise systems.',
  ],
  [
    'In Java, what file extension do you use when saving your human-readable source code file?',
    '.java',
    '.py',
    '.html',
    '.sql',
    'A',
    'Java source files end with `.java` and are compiled by `javac` into `.class` bytecode files.',
  ],
  [
    'If you declare `int age = 19;` in Java, can you store `"Nineteen"` into `age` on the next line?',
    'Yes, Java variables accept any data type at any time',
    'No, Java is statically typed, so an `int` variable can only hold whole numbers',
    'Yes, if you type it in capital letters',
    'Only on Linux computers',
    'B',
    'Static typing in Java catches mistakes early by ensuring variables only hold the type of data they were declared for.',
  ],
];

const javaModerate: RawQ[] = [
  [
    'What is the Java Collections Framework (which includes `ArrayList`, `HashMap`, and `HashSet`) used for?',
    'Providing ready-made, efficient ways to store, search, and organize groups of objects in memory',
    'Collecting physical hardware components',
    'Designing website color themes',
    'Compressing MP4 video files',
    'A',
    'Instead of building data structures from scratch, Java developers use `ArrayList` for lists and `HashMap` for key-value lookups.',
  ],
  [
    'When would you use an `ArrayList` instead of a standard fixed-size array in Java?',
    'When you never want to add any items',
    'When the number of items can grow or shrink dynamically while the program is running',
    'When you only want to store a single boolean',
    'When writing CSS animations',
    'B',
    '`ArrayList` resizes automatically as you add or remove elements.',
  ],
  [
    'In Java Object-Oriented Programming, what is the purpose of an `interface`?',
    'A graphical touchscreen monitor',
    'A tool that deletes unused files',
    'A contract that specifies what methods a class must provide, without locking in a single implementation',
    'A database password',
    'C',
    'Interfaces let different classes (e.g., `UPIPayment` and `CardPayment`) share a common set of actions (`processPayment()`).',
  ],
  [
    'What is `Spring Boot` in the Java ecosystem?',
    'A physical power button on a server rack',
    'A mobile game engine for 2D puzzles',
    'A spreadsheet calculator plugin',
    'The most popular Java framework for building modern backend web APIs and microservices quickly',
    'D',
    'Spring Boot simplifies creating production-ready web servers, REST APIs, and database-connected applications in Java.',
  ],
  [
    'In Java, why do we use `try ... catch` blocks when working with files or network connections?',
    'To handle unexpected problems (exceptions) gracefully so the application can recover instead of crashing',
    'To make the network cable longer',
    'To skip compiling the Java file',
    'To turn variables into constants',
    'A',
    'Exception handling ensures that if a file is missing or a network call fails, the program can handle it safely.',
  ],
  [
    'When comparing two `String` values for identical text in Java, why is `.equals()` used instead of `==`?',
    'Because `==` is a syntax error in Java',
    'Because `.equals()` compares the actual text characters inside the strings, whereas `==` checks if they are the exact same object in memory',
    'Because `.equals()` converts strings into integers',
    'Because `==` deletes both strings',
    'B',
    'Always use `str1.equals(str2)` in Java when checking if two strings contain the same characters.',
  ],
  [
    'What does "Inheritance" (`extends`) allow a Java class to do?',
    'Delete its parent class automatically',
    'Run without the JVM',
    'Reuse common fields and methods from an existing parent class while adding its own specialized features',
    'Convert Java code into SQL queries',
    'C',
    'Inheritance reduces code duplication by letting specialized classes (like `SavingsAccount`) build upon a base class (`BankAccount`).',
  ],
  [
    'What are build tools like `Maven` and `Gradle` used for in Java projects?',
    'Drawing user interface icons',
    'Defragmenting hard drives',
    'Writing HTML paragraphs',
    'Automatically downloading project libraries (dependencies) and packaging the Java application',
    'D',
    'Maven and Gradle manage external libraries and automate compiling, testing, and packaging Java applications.',
  ],
  [
    'If you want to look up a student’s name quickly using their unique Roll Number in Java, which collection is best suited?',
    'A `HashMap` (storing Roll Number as the key and Student Name as the value)',
    'A single `boolean` variable',
    'A `char` variable',
    'A comment block',
    'A',
    '`HashMap` stores key-value pairs and lets you find a value by its key almost instantly.',
  ],
  [
    'How does Java relate to Android mobile app development?',
    'Android phones cannot run apps written in Java',
    'Java was the original primary language for building native Android apps and shares its ecosystem with Kotlin',
    'Java is only used for desktop wallpapers on Android',
    'Android only runs C# scripts',
    'B',
    'The Android SDK was built around Java APIs, and Java/Kotlin remain the foundation of native Android development.',
  ],
];

const javaDifficult: RawQ[] = [
  [
    'Why is Java frequently chosen for backend "microservices" in large e-commerce and fintech companies?',
    'It combines strong type safety, multithreading support, mature frameworks like Spring Boot, and reliable JVM performance under heavy traffic',
    'It does not require any servers or databases',
    'It runs directly inside CSS files',
    'It only supports one user at a time',
    'A',
    'Java’s ability to handle thousands of simultaneous requests reliably makes it a staple of backend engineering.',
  ],
  [
    'What does "Encapsulation" mean when designing a Java class (such as making fields `private` and providing `public` getter/setter methods)?',
    'Encrypting the entire hard drive',
    'Protecting internal data inside a class so other parts of the program cannot accidentally corrupt it',
    'Putting all code into a single 10,000-line method',
    'Deleting all methods from a class',
    'B',
    'Encapsulation keeps a class in control of its own data and makes large codebases much safer to update.',
  ],
  [
    'In a Java web application, what is the role of an ORM like `Hibernate` or `Spring Data JPA`?',
    'Styling buttons on the webpage',
    'Cooling down the server CPU',
    'Mapping Java objects (`Student`) directly to database tables so developers can work with database records cleanly',
    'Replacing the internet connection',
    'C',
    'JPA and Hibernate bridge Java classes and relational database tables, reducing repetitive boilerplate code.',
  ],
  [
    'What is the benefit of Java’s "Multithreading" capability on a backend server?',
    'It forces the server to handle requests one by one in a slow queue',
    'It changes the programming language to Python',
    'It turns off unused monitor screens',
    'It allows a single Java server to process many user requests simultaneously across multiple CPU cores',
    'D',
    'Multithreading enables high-traffic backend applications to serve many users at the same time.',
  ],
  [
    'What are `JUnit` tests used for in a real-world Java software project?',
    'Automatically testing individual methods and classes to verify that code changes do not break existing features',
    'Designing logos for the company website',
    'Formatting USB drives',
    'Translating Java into French',
    'A',
    'Writing automated unit tests with JUnit helps teams catch bugs early and deploy updates with confidence.',
  ],
  [
    'What did Java 8+ `Streams` (such as `list.stream().filter(...).toList()`) introduce for Java developers?',
    'A video streaming player for movies',
    'A clean, readable way to filter, transform, and process collections of data without writing long manual loops',
    'A replacement for the operating system',
    'A hardware audio cable',
    'B',
    'Streams let you express data processing pipelines (like filtering active students) clearly and concisely.',
  ],
  [
    'When a Java backend application is packaged as a `.jar` file and deployed inside a Docker container, what is the advantage?',
    'The app can only run on the developer’s personal laptop',
    'The app no longer uses any RAM',
    'The app and its exact Java runtime version can run consistently on any cloud server',
    'The app becomes a static image file',
    'C',
    'Packaging a Spring Boot `.jar` inside a container makes cloud deployment predictable and repeatable.',
  ],
  [
    'How do Java and Kotlin relate to each other in modern software development?',
    'They are completely incompatible and cannot share libraries',
    'Kotlin is a CSS library',
    'Java was created after Kotlin in 2022',
    'Both compile to JVM bytecode and can work together seamlessly in the same Android or backend project',
    'D',
    'Understanding Java gives you access to the entire JVM ecosystem, including seamless interoperability with Kotlin.',
  ],
  [
    'In a team project, why are Java’s strict compiler checks helpful when 20 developers work on the same codebase?',
    'If someone changes a method parameter or return type, the compiler immediately alerts you everywhere it needs updating',
    'The compiler writes the entire business logic automatically',
    'The compiler prevents anyone from adding new classes',
    'The compiler deletes old git commits',
    'A',
    'Strong compile-time checking prevents many bugs from ever reaching production in large collaborative projects.',
  ],
  [
    'If you are interested in exploring Java further, what is a practical beginner-friendly project to build?',
    'Memorize 500 pages of JVM memory diagrams without coding',
    'Build a console-based Library/Student Management system or a simple REST API using Spring Boot',
    'Use Java to edit PNG photographs manually',
    'Write an operating system BIOS in Java',
    'B',
    'Building an Object-Oriented project or a simple Spring Boot API is a great way to experience Java’s strengths firsthand.',
  ],
];

// ============================================================================
// JAVASCRIPT — Technology Exploration & Skill Discovery Questions (Easy, Moderate, Difficult)
// ============================================================================

const jsEasy: RawQ[] = [
  [
    'Which programming language is built into every modern web browser to add interactivity to websites?',
    'C++',
    'SQL',
    'JavaScript',
    'Assembly',
    'C',
    'JavaScript is the native language of web browsers, powering interactive buttons, menus, forms, and dynamic page updates.',
  ],
  [
    'In web development, how do HTML, CSS, and JavaScript work together?',
    'They are three different names for the exact same language',
    'HTML is only for databases, CSS is for servers, and JavaScript is for cables',
    'Only one of them can be used on a website at a time',
    'HTML provides the page structure, CSS controls the visual styling, and JavaScript adds interactive behavior',
    'D',
    'HTML is the skeleton (content), CSS is the presentation (design), and JavaScript is the brain (interactivity).',
  ],
  [
    'Are "Java" and "JavaScript" the same programming language?',
    'No—despite the similar name, they are completely distinct languages with different designs and primary use cases',
    'Yes, JavaScript is just the mobile version of Java',
    'Yes, they use the exact same compiler and file extensions',
    'Java was created as a plugin for JavaScript',
    'A',
    'Java and JavaScript are separate languages; the name "JavaScript" was chosen in the 1990s mainly for marketing reasons.',
  ],
  [
    'Which of the following website features is powered by JavaScript?',
    'Defining a basic paragraph tag `<p>`',
    'Validating a registration form instantly, opening a popup modal, or updating a live score without reloading the page',
    'Plugged-in ethernet cable speed',
    'Storing physical server racks in a data center',
    'B',
    'Whenever a webpage responds dynamically to clicks, typing, or live data without a full page refresh, JavaScript is at work.',
  ],
  [
    'In modern JavaScript, which two keywords are recommended for declaring variables and constants?',
    '`int` and `float`',
    '`dim` and `set`',
    '`let` (for values that can change) and `const` (for values that stay constant)',
    '`char` and `double`',
    'C',
    'Modern JavaScript uses `let` and `const` for clean, predictable variable declarations.',
  ],
  [
    'What command do developers use in JavaScript to print helpful messages to the browser’s Developer Tools console?',
    'System.out.println()',
    'printf()',
    'std::cout',
    'console.log()',
    'D',
    '`console.log()` outputs values to the browser or Node.js console so you can inspect variables and debug code.',
  ],
  [
    'Can JavaScript also run outside the web browser on a backend server?',
    'Yes, using runtime environments like Node.js',
    'No, JavaScript can only run inside Internet Explorer',
    'Only if converted into C++ first',
    'Only on calculators',
    'A',
    'Node.js allows developers to run JavaScript on the server side, making it possible to build full-stack apps with one language.',
  ],
  [
    'What is the DOM (Document Object Model) that JavaScript interacts with in a browser?',
    'A type of hard drive cable',
    'A tree-like representation of the webpage’s HTML elements that JavaScript can read and modify dynamically',
    'A cloud billing account',
    'An antivirus program',
    'B',
    'Through the DOM, JavaScript can change text, update styles, add new elements, or respond to user clicks on the page.',
  ],
  [
    'What is `JSON` (JavaScript Object Notation) commonly used for across almost all modern web and mobile apps?',
    'Editing audio files',
    'Cooling down computer graphics cards',
    'Exchanging structured data (like user profiles or assessment scores) between a backend server and a frontend app',
    'Replacing HTML tags',
    'C',
    'JSON is a lightweight, human-readable data format used by web APIs in JavaScript, Python, Java, and almost every language.',
  ],
  [
    'When a user clicks a "Submit" button on a webpage, how does JavaScript respond to that action?',
    'By restarting the browser',
    'By deleting the HTML file',
    'By formatting the hard disk',
    'By using an Event Listener (such as a `click` handler function) that runs when the button is clicked',
    'D',
    'Event-driven programming lets JavaScript listen for user actions (`click`, `input`, `submit`, `keydown`) and react immediately.',
  ],
];

const jsModerate: RawQ[] = [
  [
    'Why do developers use frontend libraries and frameworks like `React`, `Vue`, or `Angular` with JavaScript?',
    'To build rich, interactive user interfaces out of reusable components (like `Navbar`, `ScoreCard`, and `Button`)',
    'Because browsers deleted support for HTML',
    'To write low-level operating system drivers',
    'To replace the need for CSS styling',
    'A',
    'Frameworks like React organize complex user interfaces into clean, reusable components that update automatically when data changes.',
  ],
  [
    'What is the purpose of `fetch()` (along with `async / await`) in a JavaScript web application?',
    'To physically clean the laptop keyboard',
    'To request or send data to a backend server API in the background without freezing the webpage',
    'To change the monitor brightness',
    'To install a new web browser',
    'B',
    '`fetch()` and `async/await` let web apps load data from servers smoothly while keeping the user interface responsive.',
  ],
  [
    'Suppose you have an array of student scores `[45, 78, 88, 92]` in JavaScript. What is `.filter()` used for?',
    'Deleting the entire array from memory',
    'Turning the array into a SQL database',
    'Creating a new array containing only the items that match a condition (for example, scores `>= 80`)',
    'Rebooting the server',
    'C',
    'Array methods like `.map()` and `.filter()` make transforming and filtering lists of data clean and expressive.',
  ],
  [
    'What is `TypeScript`, and why is it widely used alongside JavaScript in modern projects?',
    'A completely unrelated language used only for microcontrollers',
    'A font family for code editors',
    'A database management system',
    'A superset of JavaScript that adds optional static type checking to help catch errors before the code runs',
    'D',
    'TypeScript builds on top of JavaScript by adding type safety and better code autocomplete for growing projects.',
  ],
  [
    'In JavaScript, why is `===` (strict equality) generally preferred over `==` (loose equality)?',
    '`===` checks that both the value AND the data type match (so `5 === "5"` is `false`), avoiding surprising type conversions',
    '`===` runs only on mobile phones',
    '`==` is a syntax error in browsers',
    '`===` assigns a new value to a variable',
    'A',
    'Strict equality (`===`) prevents bugs where strings and numbers get accidentally compared as equal.',
  ],
  [
    'What can you build by combining `Node.js` and `Express` using JavaScript/TypeScript?',
    'A physical Wi-Fi router',
    'A backend web server and REST API that handles authentication, business logic, and database queries',
    'A desktop power supply unit',
    'An operating system kernel',
    'B',
    'Node.js and Express allow JavaScript developers to build fast backend servers and APIs using the same language as the frontend.',
  ],
  [
    'What is `npm` (Node Package Manager) used for in JavaScript development?',
    'Monitoring CPU fan speed',
    'Managing battery settings on Windows',
    'Installing and managing open-source JavaScript libraries and project tools (listed in `package.json`)',
    'Writing SQL table schemas',
    'C',
    '`npm` gives you access to hundreds of thousands of reusable packages—from UI icons to web servers.',
  ],
  [
    'How does `localStorage` in a web browser help a JavaScript application?',
    'It upgrades the computer’s physical hard drive to 2 TB',
    'It replaces the backend database for all users globally',
    'It encrypts the operating system',
    'It allows a web app to save small pieces of data (like a dark-mode preference or session token) in the user’s browser across page reloads',
    'D',
    '`localStorage` provides simple key-value storage right inside the user’s browser.',
  ],
  [
    'What is a template literal (using backticks like `` `Welcome, ${studentName}!` ``) in JavaScript?',
    'A convenient way to embed variables and expressions directly inside a text string',
    'A way to delete variables',
    'A comment that the browser ignores',
    'A database table name',
    'A',
    'Template literals make building dynamic messages and strings much cleaner than chaining `+` operators.',
  ],
  [
    'If you want to transform every number in `[1, 2, 3]` into `[10, 20, 30]` in JavaScript, which array method is designed for this?',
    '.pop()',
    '.map()',
    '.shift()',
    '.slice()',
    'B',
    '`.map()` applies a function to every item in an array and returns a new array of the transformed results.',
  ],
];

const jsDifficult: RawQ[] = [
  [
    'What is a Single-Page Application (SPA) built with JavaScript/React?',
    'A website that is only allowed to have one sentence of text',
    'A web app that cannot use the internet',
    'A web app that dynamically updates the current page as you navigate, providing a fast, app-like experience without full browser reloads',
    'A PDF document opened in a browser',
    'C',
    'SPAs load once and dynamically swap views and fetch JSON data from APIs, making navigation feel instant.',
  ],
  [
    'Why is JavaScript’s "asynchronous, non-blocking" nature so important in web browsers and Node.js servers?',
    'It allows the app to wait for slow network requests or database queries without freezing the screen or blocking other users',
    'It uses 100% of the CPU while doing nothing',
    'It prevents users from clicking buttons while a file downloads',
    'It runs code backwards from bottom to top',
    'A',
    'Asynchronous Promises and `async/await` keep web interfaces smooth and allow Node.js servers to handle many concurrent connections.',
  ],
  [
    'When a JavaScript frontend app calls `fetch("/api/assessments")`, what happens if the request fails due to a network drop?',
    'The computer turns off',
    'Using `try ... catch` (or `.catch()`) lets the app detect the failure and show a helpful message or fallback to the user',
    'The browser deletes the website',
    'JavaScript automatically fixes the Wi-Fi router',
    'B',
    'Handling Promise rejections with `try / catch` ensures your web app stays resilient even when network conditions are unstable.',
  ],
  [
    'Why is it a critical security rule to NEVER put secret database admin keys inside frontend JavaScript files?',
    'Because frontend JavaScript is downloaded to the user’s browser, where anyone can inspect the code and see embedded keys',
    'Because JavaScript cannot store strings longer than 10 characters',
    'Because secret keys make CSS load slowly',
    'Because browsers block files that contain the word "key"',
    'A',
    'Anything shipped to the browser is visible in Developer Tools; secret keys must stay on the backend server.',
  ],
  [
    'Beyond websites, what else can developers build using JavaScript and frameworks like React Native or Electron?',
    'Physical computer processors',
    'Cross-platform mobile apps (iOS & Android) and desktop applications (like VS Code)',
    'Automobile tires',
    'Fiber-optic cables',
    'B',
    'JavaScript’s ecosystem extends to mobile apps (React Native) and desktop apps (Electron, used to build VS Code and Slack).',
  ],
  [
    'What is the benefit of splitting a JavaScript project into ES Modules (`import` and `export` across multiple files)?',
    'It forces the browser to crash',
    'It deletes unused HTML tags',
    'It keeps code organized by responsibility (e.g., separate files for components, API calls, and utilities) so it is easy to maintain',
    'It removes the need for functions',
    'C',
    'Modular code is much easier to read, test, and collaborate on than keeping thousands of lines in a single file.',
  ],
  [
    'In a React/JavaScript application, what does "State" represent?',
    'The geographical country where the server is located',
    'A static image that never changes',
    'The operating system version',
    'Data that changes over time in response to user actions or API responses (such as the current question number or selected answer)',
    'D',
    'When state updates in a modern UI framework, the screen automatically re-renders to reflect the latest data.',
  ],
  [
    'What is the purpose of a frontend build tool like `Vite` in a modern JavaScript/TypeScript project?',
    'Providing a fast development server and bundling optimized HTML, CSS, and JavaScript assets for production deployment',
    'Designing relational database tables',
    'Replacing the operating system kernel',
    'Writing Python machine learning models',
    'A',
    'Build tools like Vite compile TypeScript/JSX and bundle your code so it loads quickly in production browsers.',
  ],
  [
    'Where is JavaScript generally NOT the first choice compared to Python or C++?',
    'Building interactive web dashboards and browser games',
    'Writing low-level operating system kernels or training massive deep-learning models from scratch on GPU clusters',
    'Creating full-stack web APIs with Node.js',
    'Building responsive frontend user interfaces',
    'B',
    'While JavaScript dominates web interfaces and full-stack apps, C/C++ leads in OS/hardware systems and Python leads in AI model training.',
  ],
  [
    'If you enjoy seeing visual results immediately and building interactive products people can use in their browser, how can you explore JavaScript further?',
    'Only read textbook definitions without opening a browser',
    'Wait until you learn assembly language first',
    'Build an interactive web project—like a quiz app, a personal portfolio, or a live dashboard that fetches data from a public API',
    'Use JavaScript only in Microsoft Word',
    'C',
    'JavaScript gives instant visual feedback in any browser, making interactive web apps a great way to learn by building.',
  ],
];

// ============================================================================
// SQL — Technology Exploration & Skill Discovery Questions (Easy, Moderate, Difficult)
// ============================================================================

const sqlEasy: RawQ[] = [
  [
    'What is SQL (Structured Query Language) mainly used for?',
    'Designing 3D animations and game graphics',
    'Storing, retrieving, filtering, and managing structured data inside relational databases',
    'Styling buttons and layouts on a webpage',
    'Controlling robotic motors directly',
    'B',
    'SQL is the standard language for communicating with relational databases like PostgreSQL, MySQL, and SQLite.',
  ],
  [
    'In a relational database, how is data organized?',
    'Into structured tables made up of rows (records) and columns (fields)',
    'Into a single giant unformatted paragraph of text',
    'Into audio MP3 tracks',
    'Into desktop wallpaper images',
    'A',
    'Relational databases organize information into clear tables—like a `students` table with columns for `id`, `name`, `email`, and `learning_level`.',
  ],
  [
    'Which basic SQL command is used to read or retrieve data from a database table?',
    'REMOVE',
    'PAINT',
    'SELECT',
    'STYLE',
    'C',
    '`SELECT` queries retrieve specific columns and rows from one or more tables (e.g., `SELECT full_name FROM students;`).',
  ],
  [
    'If you want to find only the students at the `"Easy"` level from a `students` table, which SQL clause do you use to filter the rows?',
    'COLOR BY',
    'LOOP',
    'IMPORT',
    'WHERE (for example: `WHERE learning_level = \'Easy\'`)',
    'D',
    'The `WHERE` clause filters rows so your query only returns records that match your condition.',
  ],
  [
    'Which SQL command is used to add a brand-new row of data (such as a newly registered student) into a table?',
    'INSERT INTO',
    'DELETE FROM',
    'SELECT',
    'DROP TABLE',
    'A',
    '`INSERT INTO` adds new records into a database table.',
  ],
  [
    'What is a `PRIMARY KEY` in a database table (such as `student_id`)?',
    'The password used to log into Wi-Fi',
    'A unique identifier column that ensures every row in the table can be uniquely identified and is never empty (`NULL`)',
    'The last column in every table',
    'A button on the keyboard',
    'B',
    'Every row needs a unique Primary Key (like a Roll Number or UUID) so the database never confuses two records.',
  ],
  [
    'If you want to sort a list of assessment scores from highest to lowest in SQL, which clause do you use?',
    'GROUP BY score',
    'WHERE score',
    'ORDER BY score DESC',
    'JOIN score',
    'C',
    '`ORDER BY ... DESC` sorts query results in descending order (highest to lowest), while `ASC` sorts ascending.',
  ],
  [
    'Which built-in SQL function quickly tells you how many total rows match your query?',
    'PRINT()',
    'STYLE()',
    'LOOP()',
    'COUNT()',
    'D',
    '`COUNT(*)` counts the number of rows in a table or matching group.',
  ],
  [
    'Why is SQL considered an essential skill across Web Development, Data Analytics, Data Science, and Backend Engineering?',
    'Because almost every real-world software application and data team stores and queries critical information in databases',
    'Because SQL replaces HTML and CSS in web browsers',
    'Because SQL is used to manufacture computer chips',
    'Because SQL automatically writes mobile apps',
    'A',
    'Whether you build web apps or analyze business data, SQL is the universal language for working with structured data.',
  ],
  [
    'What is the difference between `DELETE FROM students WHERE id = 5;` and `DROP TABLE students;`?',
    'They do the exact same thing',
    '`DELETE` with `WHERE` removes that specific row while keeping the table; `DROP TABLE` deletes the entire table and all its data',
    '`DROP TABLE` only renames a column',
    '`DELETE` creates a new database',
    'B',
    '`DELETE` removes matching rows, whereas `DROP TABLE` completely removes the table structure itself.',
  ],
];

const sqlModerate: RawQ[] = [
  [
    'In a real database, student profiles are in a `students` table and their test scores are in an `assessments` table. What is a SQL `JOIN` used for?',
    'Combining related rows from both tables (using a shared key like `student_id`) in a single query result',
    'Deleting both tables to save space',
    'Merging two physical computers with a cable',
    'Converting SQL into JavaScript',
    'A',
    '`JOIN` lets you connect related data across separate tables—such as viewing each student’s name alongside their assessment score.',
  ],
  [
    'What is the purpose of the `GROUP BY` clause in SQL (for example, `SELECT learning_level, COUNT(*) FROM students GROUP BY learning_level`)?',
    'Sorting names alphabetically',
    'Grouping rows that share a value so you can calculate summary totals or averages for each group (like count of students per learning level)',
    'Deleting duplicate tables',
    'Encrypting database passwords',
    'B',
    '`GROUP BY` pairs with aggregate functions (`COUNT`, `AVG`, `SUM`, `MAX`) to summarize data by category.',
  ],
  [
    'Which SQL aggregate function calculates the average value of a numeric column (such as average assessment score)?',
    'MIDDLE()',
    'TOTAL()',
    'AVG()',
    'CENTER()',
    'C',
    '`AVG(column_name)` computes the arithmetic mean of non-null values in that column.',
  ],
  [
    'What does `NULL` represent inside a SQL database column?',
    'The number zero (`0`)',
    'A text string containing the word `"NULL"`',
    'A syntax error',
    'A missing, unknown, or unrecorded value (tested using `IS NULL` or `IS NOT NULL`)',
    'D',
    'In SQL, `NULL` means a value is absent or not yet provided—which is distinct from `0` or an empty string `""`.',
  ],
  [
    'How does a `LEFT JOIN` differ from an `INNER JOIN` when matching `students` with `assessments`?',
    '`INNER JOIN` shows only students who have taken an assessment; `LEFT JOIN` shows ALL students, even those with zero assessments so far',
    '`LEFT JOIN` deletes students with no assessments',
    '`INNER JOIN` only returns the first 5 rows',
    'There is no difference between them',
    'A',
    '`LEFT JOIN` is super useful when you want to keep all records from the first table (like all registered students) regardless of whether a match exists in the second table.',
  ],
  [
    'If a student updates their college name on their Profile page, which SQL statement updates their existing row in the `students` table?',
    'INSERT INTO students ...',
    'UPDATE students SET college = ... WHERE id = ...',
    'CREATE TABLE students ...',
    'SELECT college FROM students ...',
    'B',
    '`UPDATE ... SET ... WHERE ...` modifies specific columns of existing rows that match the `WHERE` condition.',
  ],
  [
    'What is a `FOREIGN KEY` in a relational database?',
    'A key from a keyboard in another language',
    'A random number generator',
    'A column in one table (like `student_id` in `assessments`) that links to the `PRIMARY KEY` of another table (`students`)',
    'A CSS class name',
    'C',
    'Foreign keys connect related tables and ensure that every assessment record points to a valid student.',
  ],
  [
    'In a SQL query, what does `LIMIT 5` at the end of `SELECT * FROM assessments ORDER BY overall_score DESC LIMIT 5;` do?',
    'Deletes all rows after row 5',
    'Limits the database to 5 users',
    'Runs the query 5 times',
    'Returns only the top 5 rows from the sorted result',
    'D',
    '`LIMIT` restricts how many rows are returned, which is great for showing "Top 5 Scores" or "5 Most Recent Attempts".',
  ],
  [
    'What does the `LIKE` operator with `%` (such as `WHERE email LIKE \'%@gmail.com\'`) allow you to do in SQL?',
    'Search for text columns that match a specific pattern (such as all emails ending with `@gmail.com`)',
    'Add a social media "Like" button to a webpage',
    'Multiply two numbers together',
    'Create a backup of the server',
    'A',
    'In SQL `LIKE` patterns, `%` acts as a wildcard matching any sequence of characters.',
  ],
  [
    'What is the difference between `WHERE` and `HAVING` in a SQL query?',
    'They can be used interchangeably anywhere',
    '`WHERE` filters individual rows before grouping; `HAVING` filters summary groups created by `GROUP BY` (e.g., `HAVING COUNT(*) > 10`)',
    '`HAVING` is only used for deleting tables',
    '`WHERE` only works on text columns',
    'B',
    'Use `WHERE` to filter raw rows and `HAVING` to filter aggregated results after `GROUP BY`.',
  ],
];

const sqlDifficult: RawQ[] = [
  [
    'Why do developers create an `INDEX` on frequently searched columns (such as `email` or `auth_user_id`) in a database table?',
    'To make the table look colorful',
    'To double the number of columns',
    'To allow the database to find matching rows rapidly without scanning every single row in a large table',
    'To prevent anyone from running `SELECT` queries',
    'C',
    'Just like an index at the back of a textbook, a database index lets the engine jump directly to matching records.',
  ],
  [
    'How does SQL differs from procedural languages like Python, C++, or Java ("Declarative" vs "Imperative")?',
    'In SQL, you describe WHAT data you want (e.g., `SELECT ... WHERE ...`), and the database engine figures out the best way to fetch it',
    'SQL requires you to manually write `for` loops over memory pointers',
    'SQL can only be run once a week',
    'SQL does not have any keywords',
    'A',
    'SQL is a declarative language: you specify the desired result set, and the database query planner handles the step-by-step retrieval.',
  ],
  [
    'Why is it dangerous to build a SQL query by directly gluing untrusted user text into the command string (SQL Injection), and how is it prevented?',
    'It makes the font size too large; prevented by using CSS',
    'An attacker could type malicious SQL syntax to read or alter unauthorized data; prevented by using Parameterized Queries / Prepared Statements',
    'It uses too much Wi-Fi; prevented by restarting the browser',
    'It cannot happen in web applications',
    'B',
    'Parameterized queries keep user input strictly separate from SQL commands, completely preventing SQL Injection.',
  ],
  [
    'When a bank transfers ₹500 from Account A to Account B in a SQL database, why are both steps wrapped inside a `TRANSACTION`?',
    'To make the transfer take 24 hours',
    'To print a paper receipt automatically',
    'To change the currency to dollars',
    'To guarantee that either BOTH the debit and credit succeed together (`COMMIT`), or neither happens (`ROLLBACK`) if an error occurs',
    'D',
    'Database transactions ensure all-or-nothing reliability so money or data is never left in a half-updated state.',
  ],
  [
    'In data analysis with SQL, what is a Common Table Expression (`WITH summary AS (...) SELECT ...`) helpful for?',
    'Breaking a complex query into clean, readable, named step-by-step building blocks',
    'Encrypting the database server password',
    'Installing Python packages',
    'Designing mobile app icons',
    'A',
    '`WITH` clauses (CTEs) make multi-step analytical SQL queries much easier for humans to read and maintain.',
  ],
  [
    'Which modern cloud and backend platforms use PostgreSQL and SQL under the hood?',
    'Only 1980s mainframe computers',
    'Platforms like Supabase, AWS RDS, Neon, and Google Cloud SQL used by modern web and AI applications',
    'Only offline calculators',
    'CSS animation libraries',
    'B',
    'PostgreSQL (powered by SQL) is one of the fastest-growing and most widely used databases in modern cloud platforms like Supabase.',
  ],
  [
    'When a Data Analyst uses SQL in a company, what kind of real-world questions do they answer with queries?',
    'How to solder a motherboard chip',
    'Which CSS color is brightest',
    'Questions like "Which product categories grew the fastest this month?" or "What percentage of students completed both assessments?"',
    'How to cool down a server fan',
    'C',
    'SQL allows analysts and engineers to turn raw application tables into actionable insights and dashboard metrics.',
  ],
  [
    'What is a SQL `VIEW` useful for in a database?',
    'Changing the desktop wallpaper',
    'Deleting old rows automatically',
    'Upgrading the server RAM',
    'Saving a frequently used `SELECT` query as a virtual table so teams can query it easily without rewriting complex joins',
    'D',
    'Views simplify reporting and access control by presenting a saved query as if it were a regular table.',
  ],
  [
    'How do SQL databases and NoSQL document databases typically complement each other in technology?',
    'SQL databases excel at structured, relational data with strict consistency; NoSQL databases are often used for flexible, unstructured documents',
    'SQL databases cannot store text',
    'NoSQL databases do not use servers',
    'They are identical in every way',
    'A',
    'Understanding relational SQL gives you a strong foundation to evaluate when structured tables vs document stores fit a project best.',
  ],
  [
    'If you want to practice and explore SQL further, what is an effective hands-on way to learn?',
    'Design a small database schema for a real scenario (like a college event app or movie library) and write queries to answer questions from it',
    'Memorize dictionary definitions without running a single query',
    'Use SQL to style HTML headings',
    'Avoid using `JOIN` or `GROUP BY`',
    'A',
    'Practicing interactive SQL challenges (including SkillQuest’s SQL Challenge game!) and querying real tables builds confidence fast.',
  ],
];

export const JAVA_JS_SQL_QUESTIONS: QuestionRecord[] = [
  ...buildCategoryQuestions('programming', 'Java', 'java', 'Easy', javaEasy),
  ...buildCategoryQuestions('programming', 'Java', 'java', 'Moderate', javaModerate),
  ...buildCategoryQuestions('programming', 'Java', 'java', 'Difficult', javaDifficult),
  ...buildCategoryQuestions('programming', 'JavaScript', 'javascript', 'Easy', jsEasy),
  ...buildCategoryQuestions('programming', 'JavaScript', 'javascript', 'Moderate', jsModerate),
  ...buildCategoryQuestions('programming', 'JavaScript', 'javascript', 'Difficult', jsDifficult),
  ...buildCategoryQuestions('programming', 'SQL', 'sql', 'Easy', sqlEasy),
  ...buildCategoryQuestions('programming', 'SQL', 'sql', 'Moderate', sqlModerate),
  ...buildCategoryQuestions('programming', 'SQL', 'sql', 'Difficult', sqlDifficult),
];
