import { AcademicYear, AssessmentTrack, OptionKey } from '../config/constants.ts';

export interface QuestionRecord {
  id: string;
  track: AssessmentTrack;
  category: string;
  academicYear: AcademicYear;
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: OptionKey;
  explanation: string;
}

export type RawQ = [
  questionText: string,
  optionA: string,
  optionB: string,
  optionC: string,
  optionD: string,
  correctOption: OptionKey,
  explanation: string
];

export function buildCategoryQuestions(
  track: AssessmentTrack,
  category: string,
  catSlug: string,
  academicYear: AcademicYear,
  items: RawQ[]
): QuestionRecord[] {
  return items.map((item, idx) => ({
    id: `q_${catSlug}_${academicYear.toLowerCase()}_${idx + 1}`,
    track,
    category,
    academicYear,
    questionText: item[0],
    optionA: item[1],
    optionB: item[2],
    optionC: item[3],
    optionD: item[4],
    correctOption: item[5],
    explanation: item[6],
  }));
}

// ============================================================================
// PYTHON — Technology Exploration & Skill Discovery Questions (Easy, Moderate, Difficult)
// ============================================================================

const pythonEasy: RawQ[] = [
  [
    'What is Python most commonly known and used for in the technology industry?',
    'Designing physical computer motherboards',
    'Data analysis, artificial intelligence, task automation, and backend web development',
    'Styling the colors and fonts of static web pages',
    'Writing low-level BIOS firmware for calculators',
    'B',
    'Python is a versatile, beginner-friendly language widely used in AI, data science, automation scripts, and web backends.',
  ],
  [
    'Why is Python often recommended as a great first programming language for beginners?',
    'It uses clean, readable syntax that looks similar to everyday English',
    'It is the only language that computers can understand directly without any translator',
    'It requires writing long hardware memory instructions for every line',
    'It only has three keywords in total',
    'A',
    'Python was designed with readability in mind, allowing beginners to focus on problem-solving rather than complex punctuation.',
  ],
  [
    'Which of the following real-world tasks is a classic example of using Python for automation?',
    'Physically cooling down a laptop processor',
    'Increasing the screen resolution of a monitor',
    'Replacing a Wi-Fi router antenna',
    'Automatically renaming hundreds of files or generating daily summary reports from spreadsheets',
    'D',
    'Python excels at automating repetitive everyday tasks such as organizing files, reading spreadsheets, and sending notifications.',
  ],
  [
    'In Python, how does the language know which lines of code belong inside an `if` statement or a loop?',
    'By enclosing every block in angle brackets `< >`',
    'By using consistent indentation (spaces at the beginning of the line)',
    'By writing the line number at the start of every statement',
    'By coloring the text in blue',
    'B',
    'Instead of curly braces `{ }`, Python uses indentation to group code blocks cleanly and keep programs visually organized.',
  ],
  [
    'Which simple Python command is used to display a message like `"Hello, World!"` on the screen?',
    'show("Hello, World!")',
    'echo("Hello, World!")',
    'print("Hello, World!")',
    'display("Hello, World!")',
    'C',
    'The built-in `print()` function outputs text, numbers, or variables to the console.',
  ],
  [
    'If you want to store an ordered collection of items in Python—such as `["Python", "Java", "SQL"]`—which basic structure are you using?',
    'A Python List',
    'A Database Server',
    'A Web Browser',
    'A CSS Stylesheet',
    'A',
    'Square brackets `[ ]` in Python create a `list`, which lets you store, add, and organize multiple items in order.',
  ],
  [
    'Which of these popular technology areas heavily relies on Python and its rich ecosystem of libraries?',
    'Designing printed circuit boards with solder',
    'Editing raw MP3 audio cables',
    'Machine Learning and Data Science',
    'Formatting USB flash drives in BIOS',
    'C',
    'Python is the leading language for Data Science and Machine Learning thanks to libraries like NumPy, Pandas, and PyTorch.',
  ],
  [
    'What is a key characteristic of Python being an "interpreted" language?',
    'Python programs can only run on smartphones',
    'You must translate Python into Latin before running it',
    'Python code deletes itself after running once',
    'You can run Python code directly line-by-line without a separate manual compilation step first',
    'D',
    'Python runs through an interpreter, making it fast and interactive to test ideas and see results immediately.',
  ],
  [
    'In Python, what is the purpose of writing `# Calculate total marks` with a `#` symbol at the start?',
    'It deletes the variable named `total`',
    'It writes a human-readable comment that Python ignores when running the program',
    'It sends an email to the user',
    'It stops the program with an error',
    'B',
    'Comments starting with `#` help explain what the code does for yourself and other students reading your program.',
  ],
  [
    'Which type of software can you build if you learn Python web frameworks like Django or Flask?',
    'A physical ethernet cable',
    'A monitor display driver chip',
    'The backend server and APIs that power websites and web applications',
    'An optical mouse sensor',
    'C',
    'Frameworks like Django, Flask, and FastAPI let you build the server-side logic and APIs behind modern websites.',
  ],
];

const pythonModerate: RawQ[] = [
  [
    'A student wants to analyze a CSV file containing 10,000 rows of college survey data. Why is Python a popular choice for this?',
    'Python is the only language capable of opening a `.csv` file',
    'Python has powerful, easy-to-use data libraries like Pandas and Matplotlib for cleaning and visualizing data',
    'Python automatically fixes survey answers without any code',
    'CSV files are written in Python syntax',
    'B',
    'Libraries like Pandas and Matplotlib let you load spreadsheets, filter rows, calculate averages, and plot charts in just a few lines of Python.',
  ],
  [
    'What is `pip` commonly used for when working on a Python project?',
    'Installing and managing useful third-party Python packages and libraries',
    'Turning off the computer after a script finishes',
    'Converting Python files into HTML images',
    'Checking the battery percentage of a phone',
    'A',
    '`pip` is Python’s package installer, allowing you to easily add libraries for web development, data science, or automation.',
  ],
  [
    'In Python, when would you choose a `dictionary` (`{"name": "Aarav", "year": "SY"}`) instead of a simple `list`?',
    'When you only want to store a single number',
    'When you want to draw a 3D triangle on screen',
    'When you want to store and look up information using meaningful key-value pairs',
    'When you do not want to use any strings',
    'C',
    'Dictionaries store data as `key: value` pairs, making it intuitive to represent real-world records like a student profile.',
  ],
  [
    'Why do we group reusable lines of code inside a `def` function in Python?',
    'Because Python refuses to run code that is not inside a function',
    'To make the file size ten times larger',
    'To hide the code from the computer processor',
    'So we can reuse the same logic multiple times without copying and pasting code everywhere',
    'D',
    'Functions keep programs organized, reusable, and easy to read and test.',
  ],
  [
    'Which Python tool is widely used by students and data analysts to write code, view charts, and add notes in interactive blocks?',
    'Jupyter Notebook',
    'Windows Paint',
    'BIOS Setup Utility',
    'Disk Defragmenter',
    'A',
    'Jupyter Notebooks let you combine live Python code, visual charts, and explanatory notes in one interactive document.',
  ],
  [
    'If a Python program tries to divide a number by zero or open a missing file, what is `try ... except` used for?',
    'Making the computer run twice as fast',
    'Handling the error gracefully so the program can show a helpful message instead of crashing',
    'Deleting the Python file automatically',
    'Skipping all security checks on the network',
    'B',
    '`try ... except` lets your program catch unexpected errors and respond calmly without abruptly crashing.',
  ],
  [
    'What can you build using Python’s `FastAPI` or `Flask` library?',
    'A relational database engine from scratch in assembly',
    'A CSS animation stylesheet',
    'A lightweight backend web API that sends and receives JSON data for a web or mobile app',
    'A hardware graphics card',
    'C',
    'Flask and FastAPI are popular Python frameworks for creating clean backend APIs and web services.',
  ],
  [
    'When exploring Artificial Intelligence, why do most AI tutorials and projects use Python?',
    'AI models can only think in English words',
    'Other programming languages cannot perform addition or multiplication',
    'Python was invented specifically for chatbots in 2023',
    'Leading AI frameworks like TensorFlow, PyTorch, and scikit-learn provide simple Python interfaces',
    'D',
    'Python acts as the friendly interface to high-performance AI and machine learning libraries used worldwide.',
  ],
  [
    'What does `import math` or `import random` do at the top of a Python script?',
    'Brings in built-in Python modules so you can use ready-made math functions or generate random numbers',
    'Downloads a new operating system',
    'Deletes all variables in the script',
    'Connects the computer to a printer',
    'A',
    'Python comes with a rich "standard library" of modules (`math`, `random`, `datetime`, `json`) that you can import whenever needed.',
  ],
  [
    'Where does Python typically NOT act as the primary choice compared to C++ or JavaScript?',
    'Analyzing sales data and plotting charts',
    'Running interactive button animations directly inside a standard web browser tab',
    'Writing a script to automate file backups',
    'Training a machine learning model on student grades',
    'B',
    'Web browsers natively run JavaScript for interactive page animations, whereas Python typically runs on the backend server or local machine.',
  ],
];

const pythonDifficult: RawQ[] = [
  [
    'A college team is building a project that predicts house prices from historical data and exposes a web API. Why is Python ideal here?',
    'Python requires zero memory on the server',
    'Python automatically designs the mobile app icons',
    'The same language can train the machine learning model (scikit-learn) and serve it through a web API (FastAPI/Flask)',
    'Python replaces the need for an internet connection',
    'C',
    'Python bridges data science and backend web services seamlessly, making it easy to deploy ML models into real applications.',
  ],
  [
    'Why do Python developers use a "virtual environment" (`venv`) when working on multiple projects?',
    'To keep each project’s installed library versions isolated so they do not conflict with one another',
    'To simulate a 3D virtual reality headset',
    'To hide source code from git repositories',
    'To run Windows inside a calculator',
    'A',
    'Virtual environments ensure that Project A and Project B can use different library versions cleanly on the same laptop.',
  ],
  [
    'In a real-world Python backend application, how does Python typically interact with a database?',
    'By saving all user passwords in a public `.txt` file on the desktop',
    'By using a database connector or ORM (like SQLAlchemy or Supabase client) to query and store records safely',
    'By rewriting the database in HTML',
    'Python cannot connect to databases',
    'B',
    'Python backend apps communicate with databases using client libraries or Object-Relational Mappers (ORMs) like SQLAlchemy.',
  ],
  [
    'What is the advantage of Python’s "batteries-included" philosophy for software projects?',
    'Laptops running Python never need to be plugged into a charger',
    'Every Python file includes a free hardware battery',
    'Python code never needs any testing',
    'Python ships with built-in modules for working with JSON, dates, files, HTTP requests, and testing right out of the box',
    'D',
    '"Batteries-included" means Python’s standard library already includes tools for most everyday programming tasks.',
  ],
  [
    'If a Python script needs to fetch live weather information from an online service, what does it commonly use?',
    'An HTTP library like `requests` to call the weather service’s REST API and read the JSON response',
    'A physical thermometer plugged into the audio jack',
    'A CSS media query',
    'A C++ device driver',
    'A',
    'Python’s `requests` library makes it simple to fetch JSON data from web APIs in just a couple of lines of code.',
  ],
  [
    'Why are heavy numerical libraries in Python (like NumPy) still very fast even though Python itself is an interpreted language?',
    'They skip checking numbers for accuracy',
    'Their core mathematical operations are implemented in optimized C/C++ under the hood while giving you a simple Python interface',
    'They only work on arrays of size 3',
    'They run inside the computer monitor',
    'B',
    'Python combines developer productivity with C-level speed by delegating heavy array calculations to compiled libraries like NumPy.',
  ],
  [
    'Which of the following is a practical use case for Python in cybersecurity and system administration?',
    'Building physical steel locks for server room doors',
    'Replacing HTTPS certificates with plain text',
    'Writing quick scripts to scan log files, automate security checks, and test network endpoints',
    'Slowing down network routers intentionally',
    'C',
    'Security analysts and DevOps engineers frequently use Python to automate log analysis, cloud tasks, and security checks.',
  ],
  [
    'What role do type hints (such as `def greet(name: str) -> str:`) play in modern Python projects?',
    'They force the program to run only on Linux',
    'They encrypt the variable values in memory',
    'They convert Python into Java bytecode',
    'They make code easier to understand and help code editors catch mistakes early before running the program',
    'D',
    'Type hints document what kind of data a function expects and returns, improving teamwork and editor autocomplete.',
  ],
  [
    'When building a full-stack web application, how can Python and JavaScript work together?',
    'Python powers the backend API and data processing, while JavaScript powers the interactive frontend in the user’s browser',
    'Python and JavaScript cannot be used in the same project',
    'Both languages must be typed into the exact same `.html` line',
    'JavaScript compiles Python into SQL tables',
    'A',
    'Many modern tech companies use Python on the server side (for APIs and AI) paired with a JavaScript/React frontend.',
  ],
  [
    'If you enjoy logical problem solving, working with data, or automating tasks without verbose syntax, what is a great next step in Python?',
    'Memorize every function in the Python manual without writing code',
    'Build a small practical project—like a personal expense tracker, a data visualizer, or a simple web API',
    'Wait until after graduation to write your first script',
    'Only read about Python on social media',
    'B',
    'Building small, hands-on projects is the most effective way to discover which areas of Python you enjoy most.',
  ],
];

// ============================================================================
// C/C++ — Technology Exploration & Skill Discovery Questions (Easy, Moderate, Difficult)
// ============================================================================

const cppEasy: RawQ[] = [
  [
    'Which of these is a common real-world use of C and C++?',
    'Building operating systems, high-performance game engines, embedded hardware systems, and web browsers',
    'Styling text colors on a blog post using CSS',
    'Writing simple spreadsheet formulas in Microsoft Excel',
    'Designing vector logos in an image editor',
    'A',
    'C and C++ are used whenever maximum speed and direct control over computer hardware and memory are required.',
  ],
  [
    'What does it mean that C and C++ are "compiled" languages?',
    'The code can only be read by a web browser',
    'A compiler translates your human-readable source code directly into fast machine code that the computer processor executes',
    'You do not need to save the file before running it',
    'The code runs inside a Word document',
    'B',
    'Compiling translates the entire C/C++ program into native machine instructions ahead of time, resulting in very fast execution.',
  ],
  [
    'How did C++ evolve from the C programming language?',
    'C++ removed all numbers and math operations from C',
    'C++ was designed only for styling websites',
    'C++ was created as an extension of C that added Object-Oriented Programming (classes and objects) and other powerful features',
    'C and C++ have zero syntax in common',
    'C',
    'Bjarne Stroustrup developed C++ ("C with Classes") to combine C’s hardware efficiency with high-level organization for large software.',
  ],
  [
    'Why are major 3D video game engines (like Unreal Engine) primarily built using C++?',
    'Because C++ automatically draws 3D characters without any artists',
    'Because other languages cannot use a keyboard',
    'Because C++ requires no computer memory',
    'Because 3D games need to calculate graphics, physics, and frame updates in milliseconds with minimal delay',
    'D',
    'C++ gives game developers fine-grained control over CPU and memory performance so games can run smoothly at 60+ frames per second.',
  ],
  [
    'Every standard C or C++ program starts executing from which special function?',
    'start()',
    'main()',
    'begin()',
    'init()',
    'B',
    'The `main()` function is the official entry point where execution begins in every C and C++ program.',
  ],
  [
    'When working with microcontroller boards like Arduino, robotics sensors, or IoT devices, why is C/C++ used?',
    'It can run efficiently on tiny chips with very limited memory and communicate directly with hardware pins',
    'Microcontrollers have 100 GB of RAM',
    'Arduino boards run a full desktop web browser',
    'C/C++ works without electricity',
    'A',
    'Embedded systems and robotics rely on C/C++ because it produces compact code that interacts directly with hardware.',
  ],
  [
    'What does it mean that C and C++ are "statically typed" languages?',
    'Variables can never change their value once created',
    'You can only type code using a mechanical keyboard',
    'You specify the data type of a variable (such as `int`, `double`, or `char`) when declaring it, and the compiler checks it before the program runs',
    'All variables are stored as text strings',
    'C',
    'Declaring types like `int score = 95;` lets the compiler allocate the exact memory needed and catch type mistakes early.',
  ],
  [
    'In a C++ program, what is the purpose of writing `#include <iostream>` at the top of the file?',
    'It connects the program to a cloud database automatically',
    'It deletes old files on the hard drive',
    'It turns the program into a mobile app',
    'It includes the standard input/output library so your program can print to the screen (`std::cout`) and read user input (`std::cin`)',
    'D',
    'Header files like `<iostream>` provide standard tools for reading input and displaying output.',
  ],
  [
    'Learning C/C++ in college helps students understand which fundamental computer science concept deeply?',
    'How a computer actually manages memory (RAM), variables, and data structures under the hood',
    'How to post social media advertisements',
    'How to edit video clips for YouTube',
    'How to configure email spam filters',
    'A',
    'Because C/C++ stays close to the machine, learning it builds a strong foundation in how computers work internally.',
  ],
  [
    'Which of the following everyday software products relies heavily on C or C++ at its core?',
    'A simple static HTML resume page',
    'A Google Forms survey link',
    'Operating systems (Windows, Linux, macOS kernels) and web browsers (Chrome V8 engine)',
    'A plain text `.csv` list of names',
    'C',
    'Even when you run Python or JavaScript, their underlying engines and operating systems are largely written in C and C++!',
  ],
];

const cppModerate: RawQ[] = [
  [
    'In simple terms, what is a "pointer" in C/C++?',
    'The mouse cursor icon on your desktop screen',
    'A variable that stores the memory address (location in RAM) of another variable',
    'A special comment at the end of a file',
    'A button on a website form',
    'B',
    'Pointers let programs refer directly to memory locations, enabling efficient data sharing and dynamic data structures.',
  ],
  [
    'What is the Standard Template Library (STL) in C++?',
    'A built-in collection of ready-to-use data structures (like `vector`, `map`, `set`) and common algorithms (like `sort`)',
    'A collection of HTML website templates',
    'A graphic design plugin for Photoshop',
    'A cloud hosting subscription',
    'A',
    'The C++ STL saves developers from reinventing the wheel by providing fast, tested containers and algorithms.',
  ],
  [
    'In C++, why do developers usually prefer `std::vector` over a fixed-size C array when storing a list of items?',
    'A `std::vector` can only hold 3 items',
    'Fixed arrays are illegal in C++',
    'A `std::vector` can automatically grow and shrink in size as items are added or removed',
    '`std::vector` does not use computer memory',
    'C',
    '`std::vector` provides a dynamic, resizable array that manages its own memory safely and conveniently.',
  ],
  [
    'How do Object-Oriented classes and objects in C++ help when building a larger program like a game?',
    'They make the source code unreadable to humans',
    'They slow down the program intentionally',
    'They replace the `main()` function',
    'They let you model real entities (like a `Player`, `Vehicle`, or `Enemy`) by grouping their data and behaviors together',
    'D',
    'Classes act as blueprints that keep large programs modular and easier to maintain.',
  ],
  [
    'What is the difference between passing a variable "by value" vs "by reference" (`int &x`) to a function in C++?',
    'Passing by value sends a copy; passing by reference lets the function work with the original variable directly without copying it',
    'Passing by value deletes the original variable',
    'Passing by reference only works with text files',
    'There is no difference between the two',
    'A',
    'Passing by reference avoids copying large objects and allows a function to update the caller’s variable when needed.',
  ],
  [
    'Why do many competitive programming and algorithmic problem-solving platforms support C++ as a top choice?',
    'It automatically solves problems without any code',
    'Its fast execution speed and built-in STL containers (`vector`, `queue`, `map`, `sort`) make solving time-sensitive problems efficient',
    'It is the only language allowed on the internet',
    'It has no syntax rules',
    'B',
    'C++ combines rapid execution speed with convenient standard data structures.',
  ],
  [
    'What is the main trade-off of using C/C++ compared to a language like Python?',
    'C/C++ cannot perform multiplication',
    'Python runs faster on microcontrollers than C',
    'C/C++ gives higher runtime speed and hardware control, but requires more careful attention to types and memory management',
    'C/C++ programs can only be 10 lines long',
    'C',
    'Different languages have different strengths: C/C++ prioritizes performance and systems control, while Python prioritizes rapid development.',
  ],
  [
    'In C/C++, what is the role of header files (`.h` or `.hpp`) and source files (`.cpp`)?',
    'Header files are only for images',
    '`.cpp` files are only comments',
    'Both files must have the exact same text',
    'Header files declare what functions and classes exist, while `.cpp` files contain their detailed implementation code',
    'D',
    'Separating declarations (`.h`) from implementations (`.cpp`) helps organize multi-file software projects and speeds up builds.',
  ],
  [
    'Which of these fields would benefit MOST from strong C/C++ skills?',
    'Robotics, embedded systems, game engine development, and operating system engineering',
    'Designing social media banners in Canva',
    'Writing blog articles in WordPress',
    'Creating simple HTML email newsletters',
    'A',
    'Hardware-close and performance-critical domains rely heavily on C and C++.',
  ],
  [
    'In C++, what does a `string` (`std::string`) make much easier compared to old-style C character arrays (`char[]`)?',
    'Connecting to Wi-Fi networks',
    'Joining, comparing, and resizing text safely without manually tracking null-terminator bytes and buffer sizes',
    'Drawing 3D animations',
    'Installing operating system updates',
    'B',
    '`std::string` handles text length and memory automatically, making text processing in C++ much safer and simpler.',
  ],
];

const cppDifficult: RawQ[] = [
  [
    'When a team is choosing between C++ and Python for a new software module, when does C++ make the most sense?',
    'When building a quick 20-line script to rename 5 photos',
    'When creating a simple static "About Us" webpage',
    'When the module processes real-time sensor streams, audio/video frames, or high-frequency calculations where every millisecond counts',
    'When writing a basic SQL table query',
    'C',
    'Engineers choose C++ for latency-sensitive, compute-heavy, or hardware-constrained components.',
  ],
  [
    'What problem do modern C++ "Smart Pointers" (like `std::unique_ptr`) solve for developers?',
    'They automatically free memory when an object is no longer needed, preventing accidental memory leaks',
    'They make the mouse pointer move faster',
    'They translate C++ into JavaScript',
    'They connect directly to cloud storage',
    'A',
    'Modern C++ encourages using smart pointers and standard containers so memory is cleaned up automatically and safely.',
  ],
  [
    'How do C/C++ and Python often work together in fields like AI and Computer Vision (such as OpenCV or PyTorch)?',
    'They cannot be used on the same computer',
    'The heavy image and matrix math is written in C/C++ for speed, while developers call those functions easily from Python',
    'Python compiles C++ into HTML',
    'C++ is only used to print text messages',
    'B',
    'Understanding C/C++ helps you appreciate how high-speed libraries power modern AI, graphics, and scientific computing.',
  ],
  [
    'What is the difference between the "Stack" and the "Heap" in program memory?',
    'The Stack is stored on a USB drive; the Heap is stored on the monitor',
    'Both are types of SQL tables',
    'Only websites use the Stack',
    'The Stack stores fast, short-lived local variables automatically; the Heap stores dynamically allocated data that can live across functions',
    'D',
    'Knowing how stack and heap memory work gives you a clear mental model of how all programming languages manage data.',
  ],
  [
    'Why is C still widely used inside operating system kernels (like Linux) and device drivers?',
    'C has a minimal runtime footprint and maps predictably to CPU instructions and hardware registers',
    'Linux was written yesterday',
    'C automatically creates graphical user interfaces',
    'Other languages cannot use a hard drive',
    'A',
    'C’s simplicity and direct hardware mapping make it the universal language for operating system kernels and drivers.',
  ],
  [
    'In C++, what is the benefit of using `const` when passing a large object to a function (`void printReport(const Report &r)`)?',
    'It deletes the report after printing',
    'It avoids copying the large object while guaranteeing that the function will not accidentally modify it',
    'It converts the report into an integer',
    'It makes the function run on a different computer',
    'B',
    '`const` references combine the speed of pass-by-reference with the safety of read-only access.',
  ],
  [
    'What is a cross-platform build tool (such as CMake) used for in C/C++ projects?',
    'Designing website color palettes',
    'Writing SQL database backups',
    'Helping compile and build the same C/C++ project across Windows, Linux, and macOS cleanly',
    'Checking spelling in Word documents',
    'C',
    'Because C/C++ compiles to platform-specific machine code, tools like CMake automate building projects across different operating systems.',
  ],
  [
    'If an embedded system in a car’s braking controller or medical device is programmed in C/C++, why is predictable performance critical?',
    'Cars have unlimited internet bandwidth',
    'Braking controllers use web browsers to stop the car',
    'Medical devices only run once a year',
    'Real-time systems must respond within strict, guaranteed time limits without unexpected pauses',
    'D',
    'Deterministic, predictable timing is a major reason C and C++ are trusted in safety-critical embedded systems.',
  ],
  [
    'What is a "template" in C++ (such as `vector<int>` or `vector<string>`)?',
    'A feature that lets a single class or function work with different data types without rewriting the code for each type',
    'A pre-designed PowerPoint slide',
    'A database password file',
    'An HTML form element',
    'A',
    'Templates enable generic programming in C++, allowing containers like `std::vector` to hold integers, strings, or custom objects safely.',
  ],
  [
    'If you find yourself curious about how games, robotics, operating systems, or high-speed software work, how can you explore C/C++ further?',
    'Avoid writing code and only watch short social media clips',
    'Build a small console game, program an Arduino/microcontroller project, or implement classic data structures in C++',
    'Use C++ to style basic HTML paragraphs',
    'Assume C++ is only for 30-year veterans',
    'B',
    'Hands-on projects like a small 2D game (with SFML/Raylib) or an Arduino circuit make C/C++ concepts come alive quickly.',
  ],
];

export const PYTHON_AND_CPP_QUESTIONS: QuestionRecord[] = [
  ...buildCategoryQuestions('programming', 'Python', 'python', 'Easy', pythonEasy),
  ...buildCategoryQuestions('programming', 'Python', 'python', 'Moderate', pythonModerate),
  ...buildCategoryQuestions('programming', 'Python', 'python', 'Difficult', pythonDifficult),
  ...buildCategoryQuestions('programming', 'C/C++', 'cpp', 'Easy', cppEasy),
  ...buildCategoryQuestions('programming', 'C/C++', 'cpp', 'Moderate', cppModerate),
  ...buildCategoryQuestions('programming', 'C/C++', 'cpp', 'Difficult', cppDifficult),
];
